export type Post = {
  slug: string
  title: { fr: string; en: string }
  description: { fr: string; en: string }
  date: { fr: string; en: string }
  category: string
  readingTime: number
  featured?: boolean
}

export const posts: Post[] = [
  {
    slug: 'shopify-vs-nextjs-2025',
    featured: true,
    title: {
      fr: 'Shopify vs Next.js : lequel choisir pour votre commerce en 2025 ?',
      en: 'Shopify vs Next.js: Which to Choose for Your Online Store in 2025?',
    },
    description: {
      fr: 'Shopify ou Next.js pour votre e-commerce ? Nous comparons les deux solutions pour vous aider à faire le bon choix selon votre projet et vos ambitions.',
      en: 'Shopify or Next.js for your e-commerce? We compare both solutions to help you make the right choice based on your project and ambitions.',
    },
    date: { fr: 'Janvier 2025', en: 'January 2025' },
    category: 'Web & Développement',
    readingTime: 4,
  },
  {
    slug: 'nextjs-plus-rapide-que-wordpress',
    title: {
      fr: "Pourquoi un site Next.js est plus rapide qu'un site WordPress",
      en: 'Why a Next.js Site Is Faster Than a WordPress Site',
    },
    description: {
      fr: "WordPress génère ses pages à la demande, Next.js les prépare à l'avance. Cette différence fondamentale explique tout — performances, SEO, Core Web Vitals.",
      en: 'WordPress generates pages on demand, Next.js prepares them in advance. This fundamental difference explains everything — performance, SEO, Core Web Vitals.',
    },
    date: { fr: 'Janvier 2025', en: 'January 2025' },
    category: 'Web & Développement',
    readingTime: 4,
  },
  {
    slug: 'site-vitrine-professionnel-pme-locale',
    title: {
      fr: "Ce qu'un site vitrine professionnel apporte à une PME locale",
      en: 'What a Professional Website Brings to a Local SME',
    },
    description: {
      fr: "Visibilité Google, crédibilité, leads entrants — ce qu'un site vitrine bien construit change concrètement pour une PME ou un commerce de proximité.",
      en: 'Google visibility, credibility, inbound leads — what a well-built website concretely changes for an SME or local business.',
    },
    date: { fr: 'Janvier 2025', en: 'January 2025' },
    category: 'Web & Développement',
    readingTime: 4,
  },
  {
    slug: 'site-sur-mesure-vs-template',
    title: {
      fr: 'Site web sur mesure vs template : ce que votre client voit vraiment',
      en: 'Custom Website vs Template: What Your Client Really Sees',
    },
    description: {
      fr: "Un template peut ressembler à un site professionnel. Mais ce que voit votre client — et ce que lit Google — raconte une autre histoire.",
      en: "A template can look like a professional site. But what your client sees — and what Google reads — tells a different story.",
    },
    date: { fr: 'Février 2025', en: 'February 2025' },
    category: 'Web & Développement',
    readingTime: 4,
  },
  {
    slug: 'structurer-site-web-seo-conception',
    title: {
      fr: 'Comment structurer un site web pour le SEO dès la conception',
      en: 'How to Structure a Website for SEO from Day One',
    },
    description: {
      fr: "L'architecture d'un site web conditionne son SEO bien avant que le premier mot de contenu soit écrit. Voici comment l'aborder correctement dès le départ.",
      en: "A website's architecture determines its SEO long before the first word of content is written. Here's how to approach it correctly from the start.",
    },
    date: { fr: 'Février 2025', en: 'February 2025' },
    category: 'Web & Développement',
    readingTime: 5,
  },
  {
    slug: 'erreurs-vitesse-site-web',
    title: {
      fr: "Les 7 erreurs qui plombent la vitesse d'un site web",
      en: "The 7 Mistakes That Kill Your Website's Speed",
    },
    description: {
      fr: "Images non compressées, plugins inutiles, hébergement sous-dimensionné — les 7 erreurs les plus fréquentes qui ralentissent un site et comment les corriger.",
      en: "Uncompressed images, unnecessary plugins, underpowered hosting — the 7 most common mistakes that slow down a site and how to fix them.",
    },
    date: { fr: 'Février 2025', en: 'February 2025' },
    category: 'Web & Développement',
    readingTime: 5,
  },
  {
    slug: 'site-mobile-first-2025',
    title: {
      fr: 'Pourquoi votre site doit être mobile-first en 2025',
      en: 'Why Your Site Must Be Mobile-First in 2025',
    },
    description: {
      fr: "63 % du trafic web mondial vient du mobile. Google indexe en priorité la version mobile de votre site. Ce que ça implique concrètement pour votre présence en ligne.",
      en: "63% of global web traffic comes from mobile. Google primarily indexes the mobile version of your site. What this means concretely for your online presence.",
    },
    date: { fr: 'Mars 2025', en: 'March 2025' },
    category: 'Web & Développement',
    readingTime: 4,
  },
  {
    slug: 'core-web-vitals-explication',
    title: {
      fr: 'Core Web Vitals : ce que Google mesure vraiment sur votre site',
      en: 'Core Web Vitals: What Google Really Measures on Your Site',
    },
    description: {
      fr: "LCP, INP, CLS — les trois métriques que Google utilise pour évaluer l'expérience utilisateur de votre site et les intégrer dans son algorithme de classement.",
      en: "LCP, INP, CLS — the three metrics Google uses to evaluate user experience on your site and factor them into its ranking algorithm.",
    },
    date: { fr: 'Mars 2025', en: 'March 2025' },
    category: 'Web & Développement',
    readingTime: 5,
  },
  {
    slug: 'landing-page-vs-site-complet',
    title: {
      fr: 'Landing page vs site complet : quand opter pour quelle solution ?',
      en: 'Landing Page vs Full Site: When to Choose Which?',
    },
    description: {
      fr: "Une landing page ou un site complet ? La réponse dépend de votre objectif, de votre stade de développement et de ce que vous voulez que votre visiteur fasse.",
      en: "A landing page or a full site? The answer depends on your goal, your stage of development, and what you want your visitor to do.",
    },
    date: { fr: 'Mars 2025', en: 'March 2025' },
    category: 'Web & Développement',
    readingTime: 4,
  },
  {
    slug: 'systeme-reservation-sans-commission',
    title: {
      fr: 'Comment intégrer un système de réservation sans commission',
      en: 'How to Integrate a Booking System Without Commission',
    },
    description: {
      fr: "Planity, Booksy, ResaOnline prennent entre 1 % et 3 % de chaque réservation. Un système sur mesure intégré à votre site vous coûte moins et vous appartient.",
      en: "Planity, Booksy, ResaOnline take between 1% and 3% of every booking. A custom system integrated into your site costs less and belongs to you.",
    },
    date: { fr: 'Mars 2025', en: 'March 2025' },
    category: 'Web & Développement',
    readingTime: 5,
  },
  {
    slug: 'formulaire-contact-conversion',
    title: {
      fr: "Pourquoi votre formulaire de contact ne convertit pas (et comment le fixer)",
      en: "Why Your Contact Form Isn't Converting (And How to Fix It)",
    },
    description: {
      fr: "Un formulaire trop long, mal placé ou sans retour visuel fait fuir les visiteurs. Voici les erreurs les plus fréquentes et comment les corriger.",
      en: "A form that's too long, poorly placed, or lacking visual feedback drives visitors away. Here are the most common mistakes and how to fix them.",
    },
    date: { fr: 'Mars 2025', en: 'March 2025' },
    category: 'Web & Développement',
    readingTime: 5,
  },
  {
    slug: 'refonte-site-web-seo',
    title: {
      fr: "Refonte de site web : comment l'aborder sans perdre son SEO",
      en: "Website Redesign: How to Do It Without Losing Your SEO",
    },
    description: {
      fr: "Une refonte mal préparée peut effacer des mois de travail SEO en quelques jours. Voici la méthode pour migrer sans perdre vos positions Google.",
      en: "A poorly prepared redesign can erase months of SEO work in just a few days. Here's the method to migrate without losing your Google rankings.",
    },
    date: { fr: 'Avril 2025', en: 'April 2025' },
    category: 'Web & Développement',
    readingTime: 6,
  },
  {
    slug: 'seo-local-2025-guide',
    title: {
      fr: 'SEO local en 2025 : le guide complet pour les commerces de proximité',
      en: 'Local SEO in 2025: The Complete Guide for Local Businesses',
    },
    description: {
      fr: "Google Business Profile, avis clients, mots-clés locaux, schema markup — tout ce qu'il faut maîtriser pour apparaître en tête des recherches locales en 2025.",
      en: "Google Business Profile, customer reviews, local keywords, schema markup — everything you need to master to appear at the top of local search results in 2025.",
    },
    date: { fr: 'Avril 2025', en: 'April 2025' },
    category: 'SEO & Contenu',
    readingTime: 9,
  },
  {
    slug: 'impressions-google-sans-publicite',
    title: {
      fr: 'Comment passer de 0 à 800 000 impressions Google sans publicité',
      en: 'How to Go from 0 to 800,000 Google Impressions Without Advertising',
    },
    description: {
      fr: "Pas un euro en Google Ads. Sprint Motors est passé de zéro à 791 000 impressions organiques en moins de 18 mois. Voici exactement comment.",
      en: "Not a single euro in Google Ads. Sprint Motors went from zero to 791,000 organic impressions in under 18 months. Here's exactly how.",
    },
    date: { fr: 'Avril 2025', en: 'April 2025' },
    category: 'SEO & Contenu',
    readingTime: 8,
  },
  {
  slug: 'article-blog-seo-redaction',
  title: {
    fr: "Qu'est-ce qu'un article de blog SEO et comment en écrire un qui classe ?",
    en: 'What Is an SEO Blog Post and How Do You Write One That Ranks?',
  },
  description: {
    fr: "Un article de blog SEO n'est pas un article de blog ordinaire. Voici exactement comment le structurer, le rédiger et l'optimiser pour qu'il remonte sur Google.",
    en: "An SEO blog post isn't an ordinary blog post. Here's exactly how to structure, write and optimise it to rank on Google.",
  },
  date: { fr: 'Mai 2025', en: 'May 2025' },
  category: 'SEO & Contenu',
  readingTime: 7,
  },
  {
    slug: 'google-search-console-metriques',
    title: { fr: 'Google Search Console : les 5 métriques à surveiller chaque semaine', en: 'Google Search Console: The 5 Metrics to Track Every Week' },
    description: { fr: 'Impressions, clics, position moyenne, couverture d\'index, Core Web Vitals. Les 5 métriques Search Console qui comptent vraiment pour votre SEO.', en: 'Impressions, clicks, average position, index coverage, Core Web Vitals. The 5 Search Console metrics that truly matter for your SEO.' },
    date: { fr: '2 juin 2025', en: 'June 2, 2025' },
    category: 'SEO & Contenu',
    readingTime: 6,
  },
  {
    slug: 'maillage-interne-seo',
    title: { fr: 'Maillage interne : la stratégie SEO que 90 % des sites ignorent', en: 'Internal Linking: The SEO Strategy 90% of Sites Ignore' },
    description: { fr: 'Le maillage interne est l\'un des leviers SEO les plus sous-exploités. Un réseau de liens internes bien pensé renforce l\'autorité de vos pages.', en: 'Internal linking is one of the most underused SEO levers. A well-structured internal link network strengthens your pages\' authority.' },
    date: { fr: '5 juin 2025', en: 'June 5, 2025' },
    category: 'SEO & Contenu',
    readingTime: 6,
  },
  {
    slug: 'schema-markup-seo',
    title: { fr: 'Schema markup : comment aider Google à comprendre votre contenu', en: 'Schema Markup: How to Help Google Understand Your Content' },
    description: { fr: 'Le schema markup permet à Google de comprendre le sens de votre contenu et d\'afficher des rich snippets. Guide pratique pour l\'implémenter.', en: 'Schema markup helps Google understand your content\'s meaning and display rich snippets. A practical implementation guide.' },
    date: { fr: '9 juin 2025', en: 'June 9, 2025' },
    category: 'SEO & Contenu',
    readingTime: 6,
  },
  {
    slug: 'sitemap-xml-seo',
    title: { fr: 'Sitemap.xml : pourquoi c\'est indispensable et comment le générer', en: 'Sitemap.xml: Why It\'s Essential and How to Generate It' },
    description: { fr: 'Un sitemap.xml bien configuré aide Google à explorer votre site efficacement. Pourquoi c\'est indispensable et comment le générer correctement.', en: 'A well-configured sitemap.xml helps Google crawl your site efficiently. Why it\'s essential and how to generate it correctly.' },
    date: { fr: '12 juin 2025', en: 'June 12, 2025' },
    category: 'SEO & Contenu',
    readingTime: 5,
  },
  {
    slug: 'balises-meta-title-description',
    title: { fr: 'Balises meta title et description : le guide pratique 2025', en: 'Meta Title and Description Tags: The Practical Guide 2025' },
    description: { fr: 'La balise title influence directement votre classement Google. La meta description influence votre taux de clic. Comment rédiger les deux correctement.', en: 'The title tag directly influences your Google ranking. The meta description influences your click-through rate. How to write both correctly.' },
    date: { fr: '16 juin 2025', en: 'June 16, 2025' },
    category: 'SEO & Contenu',
    readingTime: 6,
  },
  {
    slug: 'mots-cles-peu-concurrentiels',
    title: { fr: 'Comment trouver des mots-clés peu concurrentiels dans votre niche', en: 'How to Find Low-Competition Keywords in Your Niche' },
    description: { fr: 'Cibler les bons mots-clés change tout. Comment identifier des requêtes à fort potentiel et faible concurrence — même sans outil payant.', en: 'Targeting the right keywords changes everything. How to identify high-potential, low-competition queries — even without a paid tool.' },
    date: { fr: '19 juin 2025', en: 'June 19, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'articles-longs-seo',
    title: { fr: 'Pourquoi les articles longs surclassent les articles courts sur Google', en: 'Why Long Articles Outrank Short Articles on Google' },
    description: { fr: 'Les articles de 1 500 à 2 500 mots occupent la majorité des premières positions Google. Pourquoi la longueur est un signal fort — et ses limites.', en: 'Articles of 1,500 to 2,500 words occupy most top Google positions. Why length is a strong signal — and its real limits.' },
    date: { fr: '23 juin 2025', en: 'June 23, 2025' },
    category: 'SEO & Contenu',
    readingTime: 6,
  },
  {
    slug: 'google-business-profile-optimisation',
    title: { fr: 'Google Business Profile : optimiser sa fiche pour le SEO local', en: 'Google Business Profile: How to Optimise Your Listing for Local SEO' },
    description: { fr: 'Google Business Profile est le levier SEO local le plus accessible. Comment l\'optimiser pour apparaître dans le pack local et convertir plus.', en: 'Google Business Profile is the most accessible local SEO lever. How to optimise it to appear in the local pack and convert more.' },
    date: { fr: '26 juin 2025', en: 'June 26, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'blog-entreprise-trafic-qualifie',
    title: { fr: 'Comment un blog d\'entreprise génère du trafic qualifié pendant des années', en: 'How a Business Blog Generates Qualified Traffic for Years' },
    description: { fr: 'Un article bien référencé continue de générer des visites 3, 5, 10 ans après publication. Comment un blog d\'entreprise devient un actif SEO durable.', en: 'A well-ranked article keeps generating visits 3, 5, 10 years after publication. How a business blog becomes a lasting SEO asset.' },
    date: { fr: '30 juin 2025', en: 'June 30, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'intention-recherche-seo',
    title: { fr: 'Intentions de recherche : comprendre ce que veut vraiment l\'utilisateur', en: 'Search Intent: Understanding What Users Really Want' },
    description: { fr: 'L\'intention de recherche est le facteur SEO numéro 1 que la plupart des sites ignorent. Comment l\'identifier et l\'exploiter pour dominer Google.', en: 'Search intent is the number-one SEO factor most sites ignore. How to identify and exploit it to dominate Google.' },
    date: { fr: '3 juillet 2025', en: 'July 3, 2025' },
    category: 'SEO & Contenu',
    readingTime: 6,
  },
  {
    slug: 'netlinking-backlinks',
    title: { fr: 'Netlinking : comment obtenir des backlinks sans spammer personne', en: 'Link Building: How to Get Backlinks Without Spamming Anyone' },
    description: { fr: 'Les backlinks restent l\'un des signaux SEO les plus puissants. Comment en obtenir naturellement, sans techniques black-hat ni spam de masse.', en: 'Backlinks remain one of the most powerful SEO signals. How to earn them naturally, without black-hat techniques or mass spam.' },
    date: { fr: '7 juillet 2025', en: 'July 7, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'crm-tpe-pme',
    title: { fr: 'Qu\'est-ce qu\'un CRM et pourquoi chaque TPE/PME en a besoin ?', en: 'What Is a CRM and Why Does Every SME Need One?' },
    description: { fr: 'Un CRM ne sert pas qu\'aux grandes entreprises. Pour une TPE ou une PME, c\'est l\'outil qui centralise les clients et automatise les relances.', en: 'A CRM isn\'t just for large companies. For an SME, it centralises clients and automates follow-ups.' },
    date: { fr: '10 juillet 2025', en: 'July 10, 2025' },
    category: 'crm',
    readingTime: 6,
  },
  {
    slug: 'crm-sur-mesure-vs-generique',
    featured: true,
    title: { fr: 'CRM sur mesure vs logiciel générique : ce que ça change en pratique', en: 'Custom CRM vs Generic Software: What It Changes in Practice' },
    description: { fr: 'Salesforce, HubSpot, Pipedrive couvrent 80 % des besoins. Le sur mesure couvre les 20 % qui font la différence pour votre métier.', en: 'Salesforce, HubSpot, Pipedrive cover 80% of needs. Custom covers the 20% that makes the difference for your trade.' },
    date: { fr: '14 juillet 2025', en: 'July 14, 2025' },
    category: 'crm',
    readingTime: 7,
  },
  {
    slug: 'automatiser-prise-rdv-artisan',
    title: { fr: 'Comment automatiser la prise de rendez-vous en ligne pour un artisan', en: 'How to Automate Online Appointment Booking for a Tradesperson' },
    description: { fr: 'Finies les heures perdues au téléphone à caler des RDV. Comment un artisan peut automatiser sa prise de rendez-vous sans logiciel complexe.', en: 'No more hours wasted on the phone scheduling appointments. How a tradesperson can automate online booking without complex software.' },
    date: { fr: '17 juillet 2025', en: 'July 17, 2025' },
    category: 'crm',
    readingTime: 6,
  },
  {
    slug: 'reservation-airbnb-vs-proprietaire',
    title: { fr: 'Système de réservation Airbnb vs solution propriétaire : bilan 2025', en: 'Airbnb vs Proprietary Booking System: 2025 Assessment' },
    description: { fr: 'Airbnb et Booking apportent de la visibilité mais prennent jusqu\'à 20 % de commission. Une solution propriétaire coûte moins et vous appartient.', en: 'Airbnb and Booking bring visibility but take up to 20% commission. A proprietary solution costs less and belongs to you.' },
    date: { fr: '22 juillet 2025', en: 'July 22, 2025' },
    category: 'crm',
    readingTime: 7,
  },
  {
    slug: 'tableau-de-bord-admin-gerant',
    title: { fr: 'Comment un tableau de bord admin change le quotidien d\'un gérant', en: 'How an Admin Dashboard Changes a Manager\'s Daily Life' },
    description: { fr: 'Un bon tableau de bord centralise réservations, clients et indicateurs en un seul endroit. Ce que ça change concrètement pour un gérant.', en: 'A good dashboard centralises bookings, clients, and indicators in one place. What it concretely changes for a manager.' },
    date: { fr: '25 juillet 2025', en: 'July 25, 2025' },
    category: 'crm',
    readingTime: 6,
  },
  {
    slug: 'fonctionnalites-crm-services',
    title: { fr: 'Les fonctionnalités indispensables d\'un CRM pour une activité de services', en: 'Essential CRM Features for a Service Business' },
    description: { fr: 'Pas toutes les fonctionnalités se valent. Pour une activité de services, les modules qui font vraiment la différence dans un CRM.', en: 'Not all features are equal. For a service business, the modules that truly make a difference in a CRM.' },
    date: { fr: '28 juillet 2025', en: 'July 28, 2025' },
    category: 'crm',
    readingTime: 6,
  },
  {
    slug: 'api-integrations-outils',
    title: { fr: 'API et intégrations : comment connecter vos outils sans coder', en: 'APIs and Integrations: How to Connect Your Tools Without Coding' },
    description: { fr: 'Calendrier, paiement, CRM, email — vos outils peuvent communiquer entre eux sans écrire une ligne de code. Comment les connecter intelligemment.', en: 'Calendar, payment, CRM, email — your tools can communicate without a single line of code. How to connect them intelligently.' },
    date: { fr: '4 août 2025', en: 'August 4, 2025' },
    category: 'crm',
    readingTime: 5,
  },
  {
    slug: 'reservations-activite-nautique',
    title: { fr: 'Comment gérer les réservations en ligne d\'une activité nautique', en: 'How to Manage Online Bookings for a Nautical Activity' },
    description: { fr: 'Location de jet-ski, paddle, bateau — les activités nautiques ont des contraintes spécifiques. Comment gérer les réservations en ligne efficacement.', en: 'Jet-ski rental, paddle, boat — nautical activities have specific constraints. How to manage online bookings effectively.' },
    date: { fr: '7 août 2025', en: 'August 7, 2025' },
    category: 'crm',
    readingTime: 7,
  },
  {
    slug: 'zero-commission-quitter-airbnb',
    title: { fr: 'Zéro commission : pourquoi les pros quittent Airbnb et Booking', en: 'Zero Commission: Why Professionals Are Leaving Airbnb and Booking' },
    description: { fr: 'Jusqu\'à 20 % de commission par réservation, des règles qui changent sans préavis. De plus en plus de professionnels reprennent le contrôle.', en: 'Up to 20% commission per booking, rules that change without notice. More professionals are taking back control.' },
    date: { fr: '11 août 2025', en: 'August 11, 2025' },
    category: 'crm',
    readingTime: 7,
  },
  {
    slug: 'dashboard-sombre-vs-clair',
    title: { fr: 'Dashboard sombre vs clair : quel impact sur la productivité ?', en: 'Dark vs Light Dashboard: What Impact on Productivity?' },
    description: { fr: 'Thème sombre ou clair pour un tableau de bord professionnel ? Au-delà de l\'esthétique, un impact réel sur la lisibilité et la fatigue visuelle.', en: 'Dark or light theme for a professional dashboard? Beyond aesthetics, a real impact on readability and visual fatigue.' },
    date: { fr: '14 août 2025', en: 'August 14, 2025' },
    category: 'crm',
    readingTime: 5,
  },
  {
    slug: 'seo-local-vente-moto-gironde',
    title: { fr: 'Comment vendre plus de motos grâce au SEO local en Gironde', en: 'How to Sell More Motorcycles Through Local SEO in Gironde' },
    description: { fr: 'Un acheteur de moto cherche d\'abord en ligne avant de visiter un concessionnaire. Comment le SEO local transforme cette recherche en vente.', en: 'A motorcycle buyer searches online before visiting a dealer. How local SEO turns that search into a sale.' },
    date: { fr: '25 août 2025', en: 'August 25, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'seo-concessionnaire-moto',
    title: { fr: 'SEO pour concessionnaire moto : les mots-clés qui convertissent', en: 'SEO for Motorcycle Dealers: The Keywords That Convert' },
    description: { fr: 'Les requêtes que vos clients tapent — moto Bordeaux, concessionnaire Honda Gironde — et comment vous positionner dessus efficacement.', en: 'The queries your clients type — motorbike Bordeaux, Honda dealer Gironde — and how to rank for them effectively.' },
    date: { fr: '16 septembre 2025', en: 'September 16, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'moto-neuve-occasion-seo',
    title: { fr: 'Moto neuve vs occasion : comment structurer les pages pour le SEO', en: 'New vs Used Motorcycle: How to Structure Pages for SEO' },
    description: { fr: 'Moto neuve et moto d\'occasion ne ciblent pas les mêmes requêtes ni les mêmes acheteurs. Comment structurer vos pages pour maximiser la visibilité des deux.', en: 'New and used bikes don\'t target the same queries or buyers. How to structure your pages to maximise visibility for both.' },
    date: { fr: '23 septembre 2025', en: 'September 23, 2025' },
    category: 'SEO & Contenu',
    readingTime: 6,
  },
  {
    slug: 'vtc-reservations-sans-application',
    title: { fr: 'Comment un VTC peut générer des réservations sans application tierce', en: 'How a VTC Driver Can Generate Bookings Without a Third-Party App' },
    description: { fr: 'Dépendre d\'Uber ou Bolt, c\'est payer 25 % de commission. Voici comment créer son propre canal de réservation direct.', en: 'Depending on Uber or Bolt means paying 25% commission. Here\'s how to create your own direct booking channel.' },
    date: { fr: '30 septembre 2025', en: 'September 30, 2025' },
    category: 'crm',
    readingTime: 7,
  },
  {
    slug: 'seo-vtc-trajets',
    title: { fr: 'SEO pour service VTC : se positionner sur les trajets clés', en: 'SEO for VTC Service: Ranking for Key Routes' },
    description: { fr: 'VTC Bordeaux aéroport, chauffeur gare Mérignac — les requêtes de trajet sont les plus rentables pour un VTC. Comment s\'y positionner.', en: 'VTC Bordeaux airport, driver Mérignac station — route queries are the most profitable for a VTC. How to rank for them.' },
    date: { fr: '10 octobre 2025', en: 'October 10, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'site-web-estheticienne',
    title: { fr: 'Site web pour esthéticienne : ce qu\'il faut absolument afficher', en: 'Website for a Beautician: What You Absolutely Must Display' },
    description: { fr: 'Un site d\'esthéticienne doit rassurer, montrer le savoir-faire et permettre la prise de RDV. Les éléments indispensables pour convertir.', en: 'A beautician\'s site must reassure, showcase expertise, and enable booking. The essential elements to convert from the first visit.' },
    date: { fr: '17 octobre 2025', en: 'October 17, 2025' },
    category: 'projets',
    readingTime: 6,
  },
  {
    slug: 'seo-local-estheticienne',
    title: { fr: 'SEO local pour une esthéticienne : se positionner dans sa ville', en: 'Local SEO for a Beautician: How to Rank in Your City' },
    description: { fr: 'Esthéticienne Bordeaux, institut beauté proche de moi — comment capter des clientes locales via Google sans budget publicitaire.', en: 'Beautician Bordeaux, beauty salon near me — how to attract local clients via Google without an advertising budget.' },
    date: { fr: '21 octobre 2025', en: 'October 21, 2025' },
    category: 'SEO & Contenu',
    readingTime: 6,
  },
  {
    slug: 'zone-intervention-sans-adresse',
    title: { fr: 'Comment afficher sa zone d\'intervention sans donner son adresse exacte', en: 'How to Display Your Service Area Without Giving Your Exact Address' },
    description: { fr: 'Beaucoup de professionnels itinérants ne veulent pas publier leur adresse personnelle. Comment indiquer votre zone de service sans compromettre votre vie privée.', en: 'Many mobile professionals don\'t want to publish their home address. How to indicate your service area without compromising privacy.' },
    date: { fr: '24 octobre 2025', en: 'October 24, 2025' },
    category: 'SEO & Contenu',
    readingTime: 5,
  },
  {
    slug: 'prise-rdv-estheticienne',
    title: { fr: 'Prise de RDV en ligne : pourquoi c\'est indispensable pour une esthéticienne', en: 'Online Appointment Booking: Why It\'s Essential for a Beautician' },
    description: { fr: 'Un formulaire de contact ne suffit plus. Pourquoi la prise de rendez-vous en ligne est devenue indispensable et comment la mettre en place.', en: 'A contact form is no longer enough. Why online appointment booking has become essential and how to set it up effectively.' },
    date: { fr: '28 octobre 2025', en: 'October 28, 2025' },
    category: 'crm',
    readingTime: 6,
  },
  {
    slug: 'estheticienne-valenciennes-seo',
    title: { fr: 'Valenciennes esthéticienne : comment capter les clientes locales sur Google', en: 'Valenciennes Beautician: How to Attract Local Clients on Google' },
    description: { fr: 'Se positionner sur esthéticienne Valenciennes demande une stratégie SEO locale précise. Les leviers qui font la différence dans une ville de taille moyenne.', en: 'Ranking for "beautician Valenciennes" requires a precise local SEO strategy. The levers that make a difference in a mid-sized city.' },
    date: { fr: '3 novembre 2025', en: 'November 3, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'choisir-agence-web-bordeaux',
    title: { fr: 'Comment choisir son agence web à Bordeaux (sans se faire avoir)', en: 'How to Choose a Web Agency in Bordeaux (Without Getting Burned)' },
    description: { fr: 'Tarifs opaques, sites génériques, délais non tenus — les mauvaises surprises existent. Comment choisir une agence web à Bordeaux en posant les bonnes questions.', en: 'Opaque pricing, generic sites, missed deadlines — bad surprises exist. How to choose a web agency in Bordeaux by asking the right questions.' },
    date: { fr: '6 novembre 2025', en: 'November 6, 2025' },
    category: 'projets',
    readingTime: 7,
  },
  {
    slug: 'site-web-meilleur-commercial',
    title: { fr: 'Pourquoi votre site web est votre meilleur commercial en 2025', en: 'Why Your Website Is Your Best Salesperson in 2025' },
    description: { fr: 'Un commercial travaille 8h par jour. Votre site web travaille 24h/24, 7j/7, sans charges sociales. Comment en faire un vrai moteur de croissance.', en: 'A salesperson works 8 hours a day. Your website works 24/7, with no social charges. How to make it a genuine growth engine.' },
    date: { fr: '10 novembre 2025', en: 'November 10, 2025' },
    category: 'projets',
    readingTime: 6,
  },
  {
    slug: 'roi-site-web',
    title: { fr: 'ROI d\'un site web : comment mesurer ce que ça vous rapporte vraiment', en: 'Website ROI: How to Measure What It Really Brings You' },
    description: { fr: 'Trafic, leads, conversions, chiffre d\'affaires généré — comment mesurer le retour sur investissement réel d\'un site web, au-delà des métriques de vanité.', en: 'Traffic, leads, conversions, revenue — how to measure a website\'s real ROI, beyond vanity metrics.' },
    date: { fr: '13 novembre 2025', en: 'November 13, 2025' },
    category: 'projets',
    readingTime: 7,
  },
  {
    slug: 'devis-ligne-vs-appel',
    title: { fr: 'Devis en ligne vs devis sur appel : lequel convertit le mieux ?', en: 'Online Quote vs Phone Quote: Which Converts Better?' },
    description: { fr: 'Formulaire de devis immédiat ou appel téléphonique d\'abord ? La réponse dépend de votre secteur, votre ticket moyen et le profil de votre client idéal.', en: 'Immediate quote form or phone call first? The answer depends on your sector, average ticket, and ideal client profile.' },
    date: { fr: '17 novembre 2025', en: 'November 17, 2025' },
    category: 'projets',
    readingTime: 6,
  },
  {
    slug: 'constructeur-site-gratuit-pme',
    title: { fr: 'Petite entreprise : pourquoi ne pas utiliser un constructeur de site gratuit', en: 'Small Business: Why Not to Use a Free Website Builder' },
    description: { fr: 'Wix, Squarespace, Webflow — ils semblent séduisants. Mais pour une PME qui veut performer sur Google et convertir, voici ce qu\'ils ne feront jamais.', en: 'Wix, Squarespace, Webflow — they seem attractive. But for an SME wanting to perform on Google, here\'s what they\'ll never do.' },
    date: { fr: '20 novembre 2025', en: 'November 20, 2025' },
    category: 'projets',
    readingTime: 7,
  },
  {
    slug: 'portfolio-ligne-clients-inbound',
    title: { fr: 'Comment un portfolio en ligne attire des clients sans prospecter', en: 'How an Online Portfolio Attracts Clients Without Prospecting' },
    description: { fr: 'Un portfolio bien construit est une machine à leads entrants. Comment transformer vos réalisations passées en arguments qui convainquent de nouveaux clients.', en: 'A well-built portfolio is an inbound lead machine. How to turn past work into arguments that convince new clients.' },
    date: { fr: '24 novembre 2025', en: 'November 24, 2025' },
    category: 'projets',
    readingTime: 6,
  },
  {
    slug: 'google-ads-vs-seo',
    title: { fr: 'Google Ads vs SEO : où investir son budget digital en premier ?', en: 'Google Ads vs SEO: Where to Invest Your Digital Budget First?' },
    description: { fr: 'Google Ads donne des résultats immédiats. Le SEO construit un actif durable. Comment décider où investir selon votre situation et vos objectifs.', en: 'Google Ads gives immediate results. SEO builds a lasting asset. How to decide where to invest based on your situation and objectives.' },
    date: { fr: '27 novembre 2025', en: 'November 27, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'mesurer-succes-site-web',
    title: { fr: 'Comment mesurer le succès d\'un site web au-delà du trafic', en: 'How to Measure Website Success Beyond Traffic' },
    description: { fr: 'Le nombre de visiteurs n\'est pas une mesure de succès. Les métriques qui indiquent si votre site convertit et génère vraiment de la valeur.', en: 'Visitor count is not a success metric. The indicators that show whether your site converts and genuinely generates value.' },
    date: { fr: '1er décembre 2025', en: 'December 1, 2025' },
    category: 'projets',
    readingTime: 6,
  },
  {
    slug: 'site-local-sans-clients-erreurs',
    title: { fr: 'Pourquoi 80 % des sites locaux ne génèrent aucun client (et comment éviter ça)', en: 'Why 80% of Local Sites Generate Zero Clients (And How to Avoid That)' },
    description: { fr: 'La plupart des sites locaux existent mais ne travaillent pas. Les 5 erreurs qui empêchent un site de générer des clients — et comment les corriger.', en: 'Most local sites exist but don\'t work. The 5 mistakes preventing a site from generating clients — and how to fix them.' },
    date: { fr: '4 décembre 2025', en: 'December 4, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'ia-creation-contenu-authenticite',
    title: { fr: 'IA et création de contenu : comment l\'utiliser sans perdre son authenticité', en: 'AI and Content Creation: How to Use It Without Losing Authenticity' },
    description: { fr: 'L\'IA peut accélérer la création de contenu. Mais utilisée sans discernement, elle produit du générique que Google et vos clients reconnaissent.', en: 'AI can accelerate content creation. But used without discernment, it produces generic content that Google and clients recognise.' },
    date: { fr: '8 décembre 2025', en: 'December 8, 2025' },
    category: 'SEO & Contenu',
    readingTime: 7,
  },
  {
    slug: 'studio-web-bordeaux-sur-mesure',
    title: { fr: 'Torquemade : l\'approche sur mesure d\'un studio web indépendant à Bordeaux', en: 'Torquemade: The Custom Approach of an Independent Web Studio in Bordeaux' },
    description: { fr: 'Pas de template. Pas d\'agence intermédiaire. Torquemade conçoit des sites et des logiciels sur mesure pour les professionnels qui veulent performer en ligne.', en: 'No templates. No intermediary agency. Torquemade designs custom sites and software for professionals who want to perform online.' },
    date: { fr: '12 décembre 2025', en: 'December 12, 2025' },
    category: 'projets',
    readingTime: 7,
  },
  {
    slug: 'connecter-stock-magasin-site-internet',
    featured: true,
    title: {
      fr: 'Comment connecter mon stock magasin à mon site internet ?',
      en: 'How do I connect my store inventory to my website?',
    },
    description: {
      fr: "Synchroniser le stock de votre commerce physique avec votre site e-commerce évite les surventes, fait gagner du temps et améliore l'expérience client. Voici comment ça marche.",
      en: "Syncing your physical store inventory with your e-commerce site prevents overselling, saves time, and improves customer experience. Here's how it works.",
    },
    date: { fr: '15 avril 2026', en: 'April 15, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 7,
  },
  {
    slug: 'temps-perdu-ressaisie-stock-manuel',
    title: {
      fr: 'Combien de temps perdez-vous à ressaisir votre stock manuellement ?',
      en: 'How much time are you losing on manual inventory entry?',
    },
    description: {
      fr: "Saisir son stock à la main, c'est plusieurs heures par semaine qui partent en fumée. Calculons ensemble le coût réel et voyons comment l'automatiser.",
      en: 'Manually entering inventory burns hours every week. Let\'s calculate the real cost and see how to automate it.',
    },
    date: { fr: '24 avril 2026', en: 'April 24, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 6,
  },
  {
    slug: 'quel-logiciel-gestion-stock-commerce-2026',
    title: {
      fr: 'Quel logiciel de gestion de stock pour un commerce physique en 2026 ?',
      en: 'Which inventory management software for a physical store in 2026?',
    },
    description: {
      fr: "Cegid, Hiboutik, EBP, Tactill, Odoo… Comment choisir le bon logiciel de stock selon votre taille, votre budget et vos besoins de connexion e-commerce.",
      en: 'Cegid, Hiboutik, EBP, Tactill, Odoo… How to choose the right inventory software based on your size, budget, and e-commerce integration needs.',
    },
    date: { fr: '8 mai 2026', en: 'May 8, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 8,
  },
  {
    slug: 'synchronisation-stock-temps-reel',
    title: {
      fr: "Synchronisation stock en temps réel : comment ça marche et pourquoi c'est indispensable",
      en: "Real-time inventory sync: how it works and why it's essential",
    },
    description: {
      fr: "Webhooks, API, push automatique : on démystifie la synchronisation stock temps réel entre votre logiciel de caisse et votre site e-commerce.",
      en: "Webhooks, APIs, automatic push: we demystify real-time inventory sync between your POS software and your e-commerce site.",
    },
    date: { fr: '19 mai 2026', en: 'May 19, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 7,
  },
  {
    slug: 'gestion-stock-excel-vs-logiciel-dedie',
    title: {
      fr: 'Gestion de stock sous Excel vs logiciel dédié : quand faire le saut ?',
      en: 'Inventory management on Excel vs dedicated software: when to make the switch?',
    },
    description: {
      fr: "Excel suffit-il vraiment pour gérer votre stock ? Voici les signaux qui montrent qu'il est temps de passer à un vrai logiciel.",
      en: "Is Excel really enough to manage your inventory? Here are the signs it's time to switch to dedicated software.",
    },
    date: { fr: '17 avril 2026', en: 'April 17, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 7,
  },
  {
    slug: '5-erreurs-sans-logiciel-gestion-stock',
    title: {
      fr: "Les 5 erreurs qui vous font perdre de l'argent sans logiciel de gestion de stock",
      en: 'The 5 mistakes costing you money without inventory management software',
    },
    description: {
      fr: "Surstockage, démarque, ruptures, ressaisie, erreurs de commande : voici les 5 fuites silencieuses d'un commerce qui gère son stock à la main.",
      en: 'Overstocking, shrinkage, stockouts, re-entry, ordering errors: the 5 silent leaks of a business managing inventory by hand.',
    },
    date: { fr: '30 avril 2026', en: 'April 30, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 6,
  },
  {
    slug: 'mise-a-jour-stock-automatique-mythe-realite',
    title: {
      fr: 'Mon stock se met à jour tout seul sur mon site : mythe ou réalité ?',
      en: 'My inventory updates automatically on my website: myth or reality?',
    },
    description: {
      fr: "Beaucoup en parlent, peu savent comment ça marche vraiment. On démêle le vrai du faux sur la mise à jour automatique du stock e-commerce.",
      en: 'Many talk about it, few know how it really works. We separate fact from fiction on automatic e-commerce inventory updates.',
    },
    date: { fr: '13 mai 2026', en: 'May 13, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 7,
  },
  {
    slug: 'woocommerce-shopify-sur-mesure-connexion-erp',
    title: {
      fr: 'WooCommerce, Shopify ou sur mesure : quelle solution pour connecter mon ERP ?',
      en: 'WooCommerce, Shopify, or custom: which solution to connect my ERP?',
    },
    description: {
      fr: "Trois philosophies, trois budgets, trois niveaux de liberté. On compare WooCommerce, Shopify et le sur mesure sous l'angle de la connexion ERP.",
      en: 'Three philosophies, three budgets, three levels of freedom. We compare WooCommerce, Shopify, and custom for ERP integration.',
    },
    date: { fr: '6 avril 2026', en: 'April 6, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 8,
  },
  {
    slug: 'vendre-en-ligne-sans-survendre',
    title: {
      fr: "Vendre en ligne sans jamais survendre : le guide de la synchronisation de stock",
      en: 'Sell online without ever overselling: a guide to inventory synchronization',
    },
    description: {
      fr: "Vendre deux fois le même produit, c'est un avis négatif assuré et une commande à rembourser. Voici comment l'éviter, vraiment.",
      en: "Selling the same product twice means a guaranteed bad review and a refund to process. Here's how to actually prevent it.",
    },
    date: { fr: '11 mai 2026', en: 'May 11, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 7,
  },
  {
    slug: 'client-commande-en-ligne-stock-magasin',
    title: {
      fr: "Un client commande en ligne, le stock baisse en magasin : voilà comment ça devrait fonctionner",
      en: "A customer orders online, store inventory drops: here's how it should actually work",
    },
    description: {
      fr: "Suivez la cascade invisible qui se déclenche en 200 millisecondes entre le bouton \"Commander\" et l'étiquette d'expédition dans votre magasin.",
      en: "Follow the invisible cascade that fires in 200 milliseconds between the \"Buy\" button and the shipping label in your store.",
    },
    date: { fr: '26 mai 2026', en: 'May 26, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 7,
  },
  {
    slug: 'connecter-sage100-shopify-sans-middleware',
    title: {
      fr: 'Comment connecter Sage 100 à Shopify sans middleware tiers',
      en: 'How to Connect Sage 100 to Shopify Without Third-Party Middleware',
    },
    description: {
      fr: "La plupart des intégrateurs vous vendent un abonnement mensuel à un outil intermédiaire. Voici comment connecter directement Sage 100 à Shopify via l'API Shopify et le Business Object Interface de Sage.",
      en: "Most integrators sell you a monthly subscription to an intermediary tool. Here's how to connect Sage 100 directly to Shopify via the Shopify API and Sage's Business Object Interface.",
    },
    date: { fr: '12 mai 2026', en: 'May 12, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 7,
  },
  {
    slug: 'pourquoi-synchro-stock-shopify-erp-plante',
    title: {
      fr: "Pourquoi la synchronisation stock Shopify-ERP plante — et comment l'éviter",
      en: 'Why Shopify-ERP Stock Sync Breaks — and How to Prevent It',
    },
    description: {
      fr: "Décalages de stock, surventes, doublons de commande : les causes sont presque toujours les mêmes. Voici les 6 erreurs d'architecture qui font échouer une intégration ERP-Shopify.",
      en: "Stock discrepancies, overselling, duplicate orders: the causes are almost always the same. Here are the 6 architecture mistakes that cause ERP-Shopify integrations to fail.",
    },
    date: { fr: '19 mai 2026', en: 'May 19, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 6,
  },
  {
    slug: 'site-ecommerce-magasin-physique-fonctions-indispensables',
    title: {
      fr: 'Site e-commerce pour un magasin physique : les 5 fonctions indispensables',
      en: 'E-Commerce Site for a Physical Store: The 5 Essential Features',
    },
    description: {
      fr: "Un site e-commerce pour un commerce physique n'a pas les mêmes priorités qu'un pure player. Voici les 5 fonctions qui font vraiment la différence quand vous avez un stock réel à gérer.",
      en: "An e-commerce site for a brick-and-mortar store has different priorities than a pure online retailer. Here are the 5 features that make the real difference when you have real inventory to manage.",
    },
    date: { fr: '26 mai 2026', en: 'May 26, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 5,
  },
  {
    slug: 'connecter-caisse-site-ecommerce-guide',
    title: {
      fr: 'Connecter sa caisse à son site e-commerce : ce que tout commerçant doit savoir avant de se lancer',
      en: 'Connecting Your POS to Your E-Commerce Site: What Every Retailer Should Know Before Starting',
    },
    description: {
      fr: "Les grandes familles de solutions pour relier un logiciel de caisse à un site marchand, leurs conditions, leurs risques contractuels et techniques — un guide honnête pour franchisés et indépendants.",
      en: "The main families of solutions for linking a POS system to an online store, their conditions, their contractual and technical risks — an honest guide for franchisees and independent retailers.",
    },
    date: { fr: '5 juin 2026', en: 'June 5, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 7,
  },
  {
    slug: '3-methodes-synchroniser-caisse-boutique-en-ligne',
    title: {
      fr: '3 méthodes pour synchroniser sa caisse et sa boutique en ligne — et les risques que personne ne mentionne',
      en: '3 Methods to Sync Your POS with Your Online Store — and the Risks No One Mentions',
    },
    description: {
      fr: "Export de fichiers, API éditeur, accès direct aux données : trois familles de solutions, leurs avantages, leurs limites et les risques contractuels et techniques associés.",
      en: "Scheduled file export, vendor API, direct database access: three families of solutions, their advantages, their limits, and the contractual and technical risks involved.",
    },
    date: { fr: '12 juin 2026', en: 'June 12, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 8,
  },
  {
    slug: 'logiciel-caisse-ecommerce-tout-en-un',
    title: {
      fr: 'La connexion caisse / e-commerce : et si le problème venait du logiciel lui-même ?',
      en: 'POS / E-Commerce Integration: What If the Problem Is the Software Itself?',
    },
    description: {
      fr: "Plateformes unifiées caisse + e-commerce : comment elles éliminent le problème de synchronisation à la source, et les vraies contraintes d'une migration (coûts, écosystème, certification NF525).",
      en: "Unified POS + e-commerce platforms: how they eliminate the synchronisation problem at the source, and the real constraints of a migration (costs, ecosystem lock-in, NF525 certification).",
    },
    date: { fr: '19 juin 2026', en: 'June 19, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 7,
  },
  {
    slug: 'why-generic-crm-fail-specialty-retail',
    title: {
      fr: 'Pourquoi les CRM génériques échouent avec les détaillants spécialisés',
      en: 'Why Generic CRMs Fail Specialty Retailers (Custom Works Better)',
    },
    description: {
      fr: 'Les CRM génériques ne sont pas conçus pour les commerces spécialisés. Voici pourquoi un CRM sur mesure se paie en quelques mois.',
      en: "Generic CRMs aren't built for specialty shops. Here's why custom CRM software pays for itself within months.",
    },
    date: { fr: '3 mai 2026', en: 'May 3, 2026' },
    category: 'crm',
    readingTime: 3,
  },
  {
    slug: 'custom-booking-system-vs-planity-booksy',
    title: {
      fr: 'Arrêtez de payer une commission sur chaque réservation',
      en: 'Stop Paying Commission-Based Booking Systems: Build Your Own',
    },
    description: {
      fr: 'Les plateformes de réservation prennent 1–3 % par réservation. Un système sur mesure intégré à votre site garde 100 % et coûte moins cher.',
      en: 'Booking platforms take 1–3% per reservation. A custom booking system integrates with your site, keeps 100% of revenue, and costs less.',
    },
    date: { fr: '26 avril 2026', en: 'April 26, 2026' },
    category: 'crm',
    readingTime: 3,
  },
  {
    slug: 'running-store-inventory-shopify-sync',
    title: {
      fr: 'Synchronisation stock en temps réel : du magasin à Shopify',
      en: 'Real-Time Stock Sync: Running Store Inventory to Shopify',
    },
    description: {
      fr: "Les magasins de running avec ventes en magasin + en ligne survendront s'ils ne synchronisent pas. Voici comment l'éviter.",
      en: "Running stores with both in-store + online sales lose sales to overselling. Here's how real-time inventory sync fixes that.",
    },
    date: { fr: '19 avril 2026', en: 'April 19, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 3,
  },
  {
    slug: 'stock-updates-spreadsheets-vs-sync',
    title: {
      fr: 'Les mises à jour de stock ne devraient jamais être manuelles',
      en: 'Stock Updates Should Be Instant, Not Spreadsheets',
    },
    description: {
      fr: 'Les mises à jour manuelles coûtent 1 875 € par an en temps. La synchronisation automatique se paie en moins de 2 ans.',
      en: 'Manual inventory updates are slow and error-prone. Automated real-time sync costs less than you think.',
    },
    date: { fr: '12 avril 2026', en: 'April 12, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 3,
  },
  {
    slug: 'inventory-software-custom-fit',
    title: {
      fr: 'Le logiciel de stock générique ne rentre pas dans votre workflow',
      en: "Off-the-Shelf Inventory Software Doesn't Fit Your Workflow",
    },
    description: {
      fr: "Les logiciels génériques couvrent 80 % de vos besoins. Les 20 % restants coûtent 500 €/mois en plugins. Pourquoi pas du sur mesure ?",
      en: "Generic inventory software solves 80% of problems. Your business isn't generic. Here's why custom makes sense.",
    },
    date: { fr: '5 avril 2026', en: 'April 5, 2026' },
    category: 'ERP & Gestion de stock',
    readingTime: 3,
  },
  {
    slug: 'bordeaux-ride-reservation-zero-commission',
    title: {
      fr: 'Comment Bordeaux Ride a construit son système de réservation zéro commission',
      en: 'How Bordeaux Ride Built Its Zero-Commission Booking System',
    },
    description: {
      fr: 'Bordeaux Ride, service de chauffeur privé premium en Gironde, a construit sa propre infrastructure de réservation pour échapper aux commissions des plateformes. Le retour d\'expérience.',
      en: 'Bordeaux Ride, a premium private driver service in Gironde, built its own booking infrastructure to escape platform commissions. Here\'s how it changed their business model.',
    },
    date: { fr: 'Juin 2026', en: 'June 2026' },
    category: 'projets',
    readingTime: 3,
  },
]
