// E.164 calling codes for every ISO 3166-1 country, bilingual names.
// Flag emoji is derived from the ISO alpha-2 code (regional indicator
// symbols) so we don't have to hand-maintain ~200 emoji.
export type PhoneCountry = {
  iso: string
  dial: string
  fr: string
  en: string
  flag: string
}

function flagFromIso(iso: string): string {
  return iso
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
}

// Target markets (CLAUDE.md) pinned first, then the rest alphabetically by French name.
const RAW: Omit<PhoneCountry, 'flag'>[] = [
  { iso: 'FR', dial: '+33', fr: 'France', en: 'France' },
  { iso: 'CH', dial: '+41', fr: 'Suisse', en: 'Switzerland' },
  { iso: 'BE', dial: '+32', fr: 'Belgique', en: 'Belgium' },
  { iso: 'CA', dial: '+1', fr: 'Canada', en: 'Canada' },
  { iso: 'US', dial: '+1', fr: 'États-Unis', en: 'United States' },
  { iso: 'GB', dial: '+44', fr: 'Royaume-Uni', en: 'United Kingdom' },

  { iso: 'AF', dial: '+93', fr: 'Afghanistan', en: 'Afghanistan' },
  { iso: 'ZA', dial: '+27', fr: 'Afrique du Sud', en: 'South Africa' },
  { iso: 'AL', dial: '+355', fr: 'Albanie', en: 'Albania' },
  { iso: 'DZ', dial: '+213', fr: 'Algérie', en: 'Algeria' },
  { iso: 'DE', dial: '+49', fr: 'Allemagne', en: 'Germany' },
  { iso: 'AD', dial: '+376', fr: 'Andorre', en: 'Andorra' },
  { iso: 'AO', dial: '+244', fr: 'Angola', en: 'Angola' },
  { iso: 'SA', dial: '+966', fr: 'Arabie saoudite', en: 'Saudi Arabia' },
  { iso: 'AR', dial: '+54', fr: 'Argentine', en: 'Argentina' },
  { iso: 'AM', dial: '+374', fr: 'Arménie', en: 'Armenia' },
  { iso: 'AU', dial: '+61', fr: 'Australie', en: 'Australia' },
  { iso: 'AT', dial: '+43', fr: 'Autriche', en: 'Austria' },
  { iso: 'AZ', dial: '+994', fr: 'Azerbaïdjan', en: 'Azerbaijan' },
  { iso: 'BS', dial: '+1242', fr: 'Bahamas', en: 'Bahamas' },
  { iso: 'BH', dial: '+973', fr: 'Bahreïn', en: 'Bahrain' },
  { iso: 'BD', dial: '+880', fr: 'Bangladesh', en: 'Bangladesh' },
  { iso: 'BB', dial: '+1246', fr: 'Barbade', en: 'Barbados' },
  { iso: 'BY', dial: '+375', fr: 'Biélorussie', en: 'Belarus' },
  { iso: 'BZ', dial: '+501', fr: 'Belize', en: 'Belize' },
  { iso: 'BJ', dial: '+229', fr: 'Bénin', en: 'Benin' },
  { iso: 'BT', dial: '+975', fr: 'Bhoutan', en: 'Bhutan' },
  { iso: 'BO', dial: '+591', fr: 'Bolivie', en: 'Bolivia' },
  { iso: 'BA', dial: '+387', fr: 'Bosnie-Herzégovine', en: 'Bosnia and Herzegovina' },
  { iso: 'BW', dial: '+267', fr: 'Botswana', en: 'Botswana' },
  { iso: 'BR', dial: '+55', fr: 'Brésil', en: 'Brazil' },
  { iso: 'BN', dial: '+673', fr: 'Brunei', en: 'Brunei' },
  { iso: 'BG', dial: '+359', fr: 'Bulgarie', en: 'Bulgaria' },
  { iso: 'BF', dial: '+226', fr: 'Burkina Faso', en: 'Burkina Faso' },
  { iso: 'BI', dial: '+257', fr: 'Burundi', en: 'Burundi' },
  { iso: 'KH', dial: '+855', fr: 'Cambodge', en: 'Cambodia' },
  { iso: 'CM', dial: '+237', fr: 'Cameroun', en: 'Cameroon' },
  { iso: 'CV', dial: '+238', fr: 'Cap-Vert', en: 'Cape Verde' },
  { iso: 'CL', dial: '+56', fr: 'Chili', en: 'Chile' },
  { iso: 'CN', dial: '+86', fr: 'Chine', en: 'China' },
  { iso: 'CY', dial: '+357', fr: 'Chypre', en: 'Cyprus' },
  { iso: 'CO', dial: '+57', fr: 'Colombie', en: 'Colombia' },
  { iso: 'KM', dial: '+269', fr: 'Comores', en: 'Comoros' },
  { iso: 'CG', dial: '+242', fr: 'Congo-Brazzaville', en: 'Congo' },
  { iso: 'CD', dial: '+243', fr: 'Congo-Kinshasa (RDC)', en: 'DR Congo' },
  { iso: 'KR', dial: '+82', fr: 'Corée du Sud', en: 'South Korea' },
  { iso: 'KP', dial: '+850', fr: 'Corée du Nord', en: 'North Korea' },
  { iso: 'CR', dial: '+506', fr: 'Costa Rica', en: 'Costa Rica' },
  { iso: 'CI', dial: '+225', fr: 'Côte d’Ivoire', en: 'Ivory Coast' },
  { iso: 'HR', dial: '+385', fr: 'Croatie', en: 'Croatia' },
  { iso: 'CU', dial: '+53', fr: 'Cuba', en: 'Cuba' },
  { iso: 'DK', dial: '+45', fr: 'Danemark', en: 'Denmark' },
  { iso: 'DJ', dial: '+253', fr: 'Djibouti', en: 'Djibouti' },
  { iso: 'EG', dial: '+20', fr: 'Égypte', en: 'Egypt' },
  { iso: 'AE', dial: '+971', fr: 'Émirats arabes unis', en: 'United Arab Emirates' },
  { iso: 'EC', dial: '+593', fr: 'Équateur', en: 'Ecuador' },
  { iso: 'ER', dial: '+291', fr: 'Érythrée', en: 'Eritrea' },
  { iso: 'ES', dial: '+34', fr: 'Espagne', en: 'Spain' },
  { iso: 'EE', dial: '+372', fr: 'Estonie', en: 'Estonia' },
  { iso: 'SZ', dial: '+268', fr: 'Eswatini', en: 'Eswatini' },
  { iso: 'ET', dial: '+251', fr: 'Éthiopie', en: 'Ethiopia' },
  { iso: 'FJ', dial: '+679', fr: 'Fidji', en: 'Fiji' },
  { iso: 'FI', dial: '+358', fr: 'Finlande', en: 'Finland' },
  { iso: 'GA', dial: '+241', fr: 'Gabon', en: 'Gabon' },
  { iso: 'GM', dial: '+220', fr: 'Gambie', en: 'Gambia' },
  { iso: 'GE', dial: '+995', fr: 'Géorgie', en: 'Georgia' },
  { iso: 'GH', dial: '+233', fr: 'Ghana', en: 'Ghana' },
  { iso: 'GR', dial: '+30', fr: 'Grèce', en: 'Greece' },
  { iso: 'GD', dial: '+1473', fr: 'Grenade', en: 'Grenada' },
  { iso: 'GT', dial: '+502', fr: 'Guatemala', en: 'Guatemala' },
  { iso: 'GN', dial: '+224', fr: 'Guinée', en: 'Guinea' },
  { iso: 'GQ', dial: '+240', fr: 'Guinée équatoriale', en: 'Equatorial Guinea' },
  { iso: 'GW', dial: '+245', fr: 'Guinée-Bissau', en: 'Guinea-Bissau' },
  { iso: 'GY', dial: '+592', fr: 'Guyana', en: 'Guyana' },
  { iso: 'HT', dial: '+509', fr: 'Haïti', en: 'Haiti' },
  { iso: 'HN', dial: '+504', fr: 'Honduras', en: 'Honduras' },
  { iso: 'HU', dial: '+36', fr: 'Hongrie', en: 'Hungary' },
  { iso: 'IN', dial: '+91', fr: 'Inde', en: 'India' },
  { iso: 'ID', dial: '+62', fr: 'Indonésie', en: 'Indonesia' },
  { iso: 'IQ', dial: '+964', fr: 'Irak', en: 'Iraq' },
  { iso: 'IR', dial: '+98', fr: 'Iran', en: 'Iran' },
  { iso: 'IE', dial: '+353', fr: 'Irlande', en: 'Ireland' },
  { iso: 'IS', dial: '+354', fr: 'Islande', en: 'Iceland' },
  { iso: 'IL', dial: '+972', fr: 'Israël', en: 'Israel' },
  { iso: 'IT', dial: '+39', fr: 'Italie', en: 'Italy' },
  { iso: 'JM', dial: '+1876', fr: 'Jamaïque', en: 'Jamaica' },
  { iso: 'JP', dial: '+81', fr: 'Japon', en: 'Japan' },
  { iso: 'JO', dial: '+962', fr: 'Jordanie', en: 'Jordan' },
  { iso: 'KZ', dial: '+7', fr: 'Kazakhstan', en: 'Kazakhstan' },
  { iso: 'KE', dial: '+254', fr: 'Kenya', en: 'Kenya' },
  { iso: 'KG', dial: '+996', fr: 'Kirghizistan', en: 'Kyrgyzstan' },
  { iso: 'KW', dial: '+965', fr: 'Koweït', en: 'Kuwait' },
  { iso: 'LA', dial: '+856', fr: 'Laos', en: 'Laos' },
  { iso: 'LS', dial: '+266', fr: 'Lesotho', en: 'Lesotho' },
  { iso: 'LV', dial: '+371', fr: 'Lettonie', en: 'Latvia' },
  { iso: 'LB', dial: '+961', fr: 'Liban', en: 'Lebanon' },
  { iso: 'LR', dial: '+231', fr: 'Libéria', en: 'Liberia' },
  { iso: 'LY', dial: '+218', fr: 'Libye', en: 'Libya' },
  { iso: 'LI', dial: '+423', fr: 'Liechtenstein', en: 'Liechtenstein' },
  { iso: 'LT', dial: '+370', fr: 'Lituanie', en: 'Lithuania' },
  { iso: 'LU', dial: '+352', fr: 'Luxembourg', en: 'Luxembourg' },
  { iso: 'MK', dial: '+389', fr: 'Macédoine du Nord', en: 'North Macedonia' },
  { iso: 'MG', dial: '+261', fr: 'Madagascar', en: 'Madagascar' },
  { iso: 'MY', dial: '+60', fr: 'Malaisie', en: 'Malaysia' },
  { iso: 'MW', dial: '+265', fr: 'Malawi', en: 'Malawi' },
  { iso: 'MV', dial: '+960', fr: 'Maldives', en: 'Maldives' },
  { iso: 'ML', dial: '+223', fr: 'Mali', en: 'Mali' },
  { iso: 'MT', dial: '+356', fr: 'Malte', en: 'Malta' },
  { iso: 'MA', dial: '+212', fr: 'Maroc', en: 'Morocco' },
  { iso: 'MU', dial: '+230', fr: 'Maurice', en: 'Mauritius' },
  { iso: 'MR', dial: '+222', fr: 'Mauritanie', en: 'Mauritania' },
  { iso: 'MX', dial: '+52', fr: 'Mexique', en: 'Mexico' },
  { iso: 'MD', dial: '+373', fr: 'Moldavie', en: 'Moldova' },
  { iso: 'MC', dial: '+377', fr: 'Monaco', en: 'Monaco' },
  { iso: 'MN', dial: '+976', fr: 'Mongolie', en: 'Mongolia' },
  { iso: 'ME', dial: '+382', fr: 'Monténégro', en: 'Montenegro' },
  { iso: 'MZ', dial: '+258', fr: 'Mozambique', en: 'Mozambique' },
  { iso: 'MM', dial: '+95', fr: 'Myanmar', en: 'Myanmar' },
  { iso: 'NA', dial: '+264', fr: 'Namibie', en: 'Namibia' },
  { iso: 'NP', dial: '+977', fr: 'Népal', en: 'Nepal' },
  { iso: 'NI', dial: '+505', fr: 'Nicaragua', en: 'Nicaragua' },
  { iso: 'NE', dial: '+227', fr: 'Niger', en: 'Niger' },
  { iso: 'NG', dial: '+234', fr: 'Nigéria', en: 'Nigeria' },
  { iso: 'NO', dial: '+47', fr: 'Norvège', en: 'Norway' },
  { iso: 'NZ', dial: '+64', fr: 'Nouvelle-Zélande', en: 'New Zealand' },
  { iso: 'OM', dial: '+968', fr: 'Oman', en: 'Oman' },
  { iso: 'UG', dial: '+256', fr: 'Ouganda', en: 'Uganda' },
  { iso: 'UZ', dial: '+998', fr: 'Ouzbékistan', en: 'Uzbekistan' },
  { iso: 'PK', dial: '+92', fr: 'Pakistan', en: 'Pakistan' },
  { iso: 'PA', dial: '+507', fr: 'Panama', en: 'Panama' },
  { iso: 'PG', dial: '+675', fr: 'Papouasie-Nouvelle-Guinée', en: 'Papua New Guinea' },
  { iso: 'PY', dial: '+595', fr: 'Paraguay', en: 'Paraguay' },
  { iso: 'NL', dial: '+31', fr: 'Pays-Bas', en: 'Netherlands' },
  { iso: 'PE', dial: '+51', fr: 'Pérou', en: 'Peru' },
  { iso: 'PH', dial: '+63', fr: 'Philippines', en: 'Philippines' },
  { iso: 'PL', dial: '+48', fr: 'Pologne', en: 'Poland' },
  { iso: 'PF', dial: '+689', fr: 'Polynésie française', en: 'French Polynesia' },
  { iso: 'PT', dial: '+351', fr: 'Portugal', en: 'Portugal' },
  { iso: 'QA', dial: '+974', fr: 'Qatar', en: 'Qatar' },
  { iso: 'RO', dial: '+40', fr: 'Roumanie', en: 'Romania' },
  { iso: 'RU', dial: '+7', fr: 'Russie', en: 'Russia' },
  { iso: 'RW', dial: '+250', fr: 'Rwanda', en: 'Rwanda' },
  { iso: 'SV', dial: '+503', fr: 'Salvador', en: 'El Salvador' },
  { iso: 'WS', dial: '+685', fr: 'Samoa', en: 'Samoa' },
  { iso: 'SN', dial: '+221', fr: 'Sénégal', en: 'Senegal' },
  { iso: 'RS', dial: '+381', fr: 'Serbie', en: 'Serbia' },
  { iso: 'SC', dial: '+248', fr: 'Seychelles', en: 'Seychelles' },
  { iso: 'SL', dial: '+232', fr: 'Sierra Leone', en: 'Sierra Leone' },
  { iso: 'SG', dial: '+65', fr: 'Singapour', en: 'Singapore' },
  { iso: 'SK', dial: '+421', fr: 'Slovaquie', en: 'Slovakia' },
  { iso: 'SI', dial: '+386', fr: 'Slovénie', en: 'Slovenia' },
  { iso: 'SO', dial: '+252', fr: 'Somalie', en: 'Somalia' },
  { iso: 'SD', dial: '+249', fr: 'Soudan', en: 'Sudan' },
  { iso: 'SS', dial: '+211', fr: 'Soudan du Sud', en: 'South Sudan' },
  { iso: 'LK', dial: '+94', fr: 'Sri Lanka', en: 'Sri Lanka' },
  { iso: 'SE', dial: '+46', fr: 'Suède', en: 'Sweden' },
  { iso: 'SR', dial: '+597', fr: 'Suriname', en: 'Suriname' },
  { iso: 'SY', dial: '+963', fr: 'Syrie', en: 'Syria' },
  { iso: 'TJ', dial: '+992', fr: 'Tadjikistan', en: 'Tajikistan' },
  { iso: 'TW', dial: '+886', fr: 'Taïwan', en: 'Taiwan' },
  { iso: 'TZ', dial: '+255', fr: 'Tanzanie', en: 'Tanzania' },
  { iso: 'TD', dial: '+235', fr: 'Tchad', en: 'Chad' },
  { iso: 'CZ', dial: '+420', fr: 'Tchéquie', en: 'Czechia' },
  { iso: 'TH', dial: '+66', fr: 'Thaïlande', en: 'Thailand' },
  { iso: 'TL', dial: '+670', fr: 'Timor oriental', en: 'East Timor' },
  { iso: 'TG', dial: '+228', fr: 'Togo', en: 'Togo' },
  { iso: 'TO', dial: '+676', fr: 'Tonga', en: 'Tonga' },
  { iso: 'TT', dial: '+1868', fr: 'Trinité-et-Tobago', en: 'Trinidad and Tobago' },
  { iso: 'TN', dial: '+216', fr: 'Tunisie', en: 'Tunisia' },
  { iso: 'TM', dial: '+993', fr: 'Turkménistan', en: 'Turkmenistan' },
  { iso: 'TR', dial: '+90', fr: 'Turquie', en: 'Turkey' },
  { iso: 'UA', dial: '+380', fr: 'Ukraine', en: 'Ukraine' },
  { iso: 'UY', dial: '+598', fr: 'Uruguay', en: 'Uruguay' },
  { iso: 'VU', dial: '+678', fr: 'Vanuatu', en: 'Vanuatu' },
  { iso: 'VA', dial: '+379', fr: 'Vatican', en: 'Vatican City' },
  { iso: 'VE', dial: '+58', fr: 'Venezuela', en: 'Venezuela' },
  { iso: 'VN', dial: '+84', fr: 'Vietnam', en: 'Vietnam' },
  { iso: 'YE', dial: '+967', fr: 'Yémen', en: 'Yemen' },
  { iso: 'ZM', dial: '+260', fr: 'Zambie', en: 'Zambia' },
  { iso: 'ZW', dial: '+263', fr: 'Zimbabwe', en: 'Zimbabwe' },
]

export const PHONE_COUNTRIES: PhoneCountry[] = RAW.map((c) => ({ ...c, flag: flagFromIso(c.iso) }))
