export type Lang = 'fr' | 'en'

export const strings = {
  fr: {
    nav: {
      work: 'Projets',
      about: 'À propos',
      contact: 'Contact',
      cta: 'Démarrer un projet →',
    },
    hero: {
      eyebrow: 'Studio',
      headline1: 'Web dev & CRM sur mesure.',
      headline2: 'Du design à la base de données.',
      sub: 'Nous construisons des sites qui performent — et les systèmes derrière.',
      cta1: 'Voir les projets',
      cta2: 'Nous contacter',
    },
    stats: [
      { value: '1M+', label: 'Impressions Google' },
      { value: '15+',   label: 'Projets livrés' },
      { value: '100%',  label: 'Délais respectés' },
    ],
    services: {
      eyebrow: 'Services',
      title: 'Ce qu\'on construit.',
      items: [
        {
          num: '01',
          title: 'Sites web',
          desc: 'Construits de zéro. Mobile-first, SEO-ready, livraison en 15 jours ouvrés.',
        },
        {
          num: '02',
          title: 'CRM & Logiciel sur mesure',
          desc: 'Systèmes de réservation, CRM sur mesure pour votre entreprise, dashboards — construits autour de votre workflow exact.',
        },
        {
          num: '03',
          title: 'SEO & Optimisation IA',
          desc: 'Contenu qui rank sur Google ET dans les réponses AI : ChatGPT, Perplexity, Claude, et autres.',
        },
        {
          num: '04',
          title: 'Gestion d\'inventaire',
          desc: 'Ajout, modification et suppression de stock depuis votre téléphone — en 2 minutes chrono.',
        },
      ],
    },
    workPreview: {
      eyebrow: 'Projets à la une',
      title: 'Des sites qui performent, pas juste de beaux designs.',
      cta: 'Voir tous les projets →',
    },
    testimonials: {
      eyebrow: 'Avis clients',
      title: 'Ce que disent nos clients.',
      items: [
        {
          quote: 'Loan a pris le temps d\'écouter et a proposé les solutions les plus adaptées. Le site a eu un impact énorme sur notre activité — les retours sont extrêmement positifs. Nous lui avons ensuite confié 2 missions supplémentaires pour mettre en avant 2 marques importantes via 2 sites séparés, avec le même résultat. Nous recommandons Loan pour sa disponibilité et son professionnalisme.',
          name: 'Pierre',
          role: 'Commercial · Sprint Motors, Bordeaux',
          url: 'https://sprintmotors.com',
          initials: 'P',
        },
        {
          quote: 'Je recommande vivement le professionnalisme de Loan pour la création de site web. Il a su écouter mes demandes et comprendre rapidement mes attentes. Je suis extrêmement satisfait de son travail. Merci pour la qualité, la disponibilité et la rapidité.',
          name: 'Paul',
          role: 'Gérant · Moto Passion 65, Tarbes',
          url: 'https://motopassion65.com',
          initials: 'P',
        },
      ],
    },
    cta: {
      title: 'Parlons de votre projet.',
      sub: 'Remplissez le formulaire, on revient vers vous dans les 24h. Pas de pitch, pas de pression.',
      button: 'Démarrer une conversation',
    },
    work: {
      eyebrow: 'Projets',
      headline: 'Projets à la une.',
      sub: 'De vrais projets , avec des métriques réelles — tirées de Google Search Console et GA4.',
      filterAll: 'Tous',
      filterWeb: 'Sites web',
      filterLogiciel: 'CRM & Systèmes',
      filterSeo: 'SEO & Contenu',
      visitSite: 'Voir le site →',
      noMatch: 'Aucun projet ne correspond à ce filtre.',
      ctaTitle: 'Parlons de votre projet.',
      ctaSub: 'Remplissez le formulaire, on revient vers vous dans les 24h. Pas de pitch, pas de pression.',
      ctaButton: 'Démarrer un projet',
    },
    about: {
      eyebrow: 'À propos',
      headline: 'Un site qui convertit vaut mieux qu\'un site qui impressionne.',
      sub: 'Un seul interlocuteur, du brief au lancement. Avec un objectif en tête : votre ROI.',
      whyEyebrow: 'Différenciateurs',
      whyTitle: 'Ce qui nous différencie.',
      differentiators: [
        { title: 'Livraison en 15 jours', text: 'Du début du projet à la livraison du  site live — 15 jours ouvrés. Pas de blabla, pas d\'attente inutile.' },
        { title: 'Métriques réelles uniquement', text: 'Chaque décision est basée sur Search Console et GA4. Pas d\'estimations, pas de spin.' },
        { title: 'Pas de template', text: 'Chaque site est construit de zéro autour de votre business. Aucun thème prémâché.' },
        { title: 'Support post-lancement', text: 'Disponible après le lancement. Analyses mensuelles, mises à jour, évolutions.' },
        { title: 'Interlocuteur unique', text: 'Un seul contact du début à la fin. Pas de chef de projet qui relaie, pas de junior.' },
        { title: 'Visible sur l\'IA', text: 'Vos pages sont structurées pour apparaître dans ChatGPT, Claude et Perplexity et autres.' },
      ],
      statsEyebrow: 'En chiffres',
      stats: [
        { value: '15+',    label: 'Projets livrés' },
        { value: '1M+',  label: 'Impressions Google' },
        { value: '100%',   label: 'Délais respectés' },
      ],
      ctaTitle: 'Prêt pour un site qui performe vraiment ?',
      ctaSub: 'Parlez-nous de votre projet. Nous répondons vite et vous disons honnêtement si nous sommes la bonne solution.',
      ctaButton: 'Démarrer une conversation',
    },
    contact: {
      eyebrow: 'Contact',
      headline: 'Parlons de votre projet.',
      sub: 'Remplissez le formulaire ci-dessous, nous revenons vers vous dans les 24h. Pas de pitch, pas de pression.',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'Email',
      company: 'Entreprise / Projet',
      serviceLabel: 'Ce que vous cherchez',
      services: ['Site web', 'CRM sur mesure', 'SEO & Contenu', 'Pas encore sûr(e)'],
      message: 'Message (optionnel)',
      submit: 'Envoyer →',
      success: '✓ Message envoyé — nous revenons vers vous dans les 24h.',
      error: 'Une erreur s\'est produite. Envoyez-nous un email : loanrmb@gmail.com',
    },
    footer: {
      tagline: 'Web dev & CRM sur mesure.',
      nav: ['Projets', 'À propos', 'Contact'],
      navHref: ['/work', '/about', '/contact'],
      copy: '© 2025 Torquemade.',
      email: 'loanrmb@gmail.com',
    },
  },

  en: {
    nav: {
      work: 'Work',
      about: 'About',
      contact: 'Contact',
      cta: 'Start a project →',
    },
    hero: {
      eyebrow: 'Studio',
      headline1: 'Custom web dev & CRM.',
      headline2: 'From design to database.',
      sub: 'We build sites that perform — and the systems behind them.',
      cta1: 'See our work',
      cta2: 'Get in touch',
    },
    stats: [
      { value: '1M+', label: 'Google impressions' },
      { value: '15+',   label: 'Projects delivered' },
      { value: '100%',  label: 'Deadlines met' },
    ],
    services: {
      eyebrow: 'Services',
      title: 'What we build.',
      items: [
        {
          num: '01',
          title: 'Websites',
          desc: 'Built from scratch. Mobile-first, SEO-ready, delivered in 15 business days.',
        },
        {
          num: '02',
          title: 'Custom CRM & Software',
          desc: 'Booking systems, tailored CRMs, dashboards — built around your exact workflow.',
        },
        {
          num: '03',
          title: 'SEO & AI Optimization',
          desc: 'Content that ranks on Google AND appears in AI answers: ChatGPT, Perplexity, Claude & other models.',
        },
        {
          num: '04',
          title: 'Inventory Management',
          desc: 'Add, edit, and remove stock from your phone — in 2 minutes flat.',
        },
      ],
    },
    workPreview: {
      eyebrow: 'Featured work',
      title: 'Sites that perform, not just look good.',
      cta: 'See all projects →',
    },
    testimonials: {
      eyebrow: 'Client reviews',
      title: 'What our clients say.',
      items: [
        {
          quote: 'Loan took the time to listen and proposed the most adapted solutions. The website had a huge impact on our business — the feedback has been extremely positive. We then entrusted him with 2 additional missions to highlight 2 important brands through 2 separate sites, with the same result. We highly recommend Loan for his availability and professionalism.',
          name: 'Pierre',
          role: 'Salesman · Sprint Motors, Bordeaux',
          url: 'https://sprintmotors.com',
          initials: 'P',
        },
        {
          quote: 'I highly recommend Loan\'s professionalism for website creation. He listened to my requests and quickly understood my expectations. I am extremely satisfied with his work. Thank you for the quality, availability, and speed.',
          name: 'Paul',
          role: 'Owner · Moto Passion 65, Tarbes',
          url: 'https://motopassion65.com',
          initials: 'P',
        },
      ],
    },
    cta: {
      title: 'Let\'s build something.',
      sub: 'Fill in the form, I\'ll get back to you within 24h. No pitch, no pressure.',
      button: 'Start a conversation',
    },
    work: {
      eyebrow: 'Work',
      headline: 'Featured work.',
      sub: 'Real projects, real metrics — pulled directly from Google Search Console and GA4.',
      filterAll: 'All',
      filterWeb: 'Websites',
      filterLogiciel: 'CRM & Systems',
      filterSeo: 'SEO & Content',
      visitSite: 'Visit site →',
      noMatch: 'No projects match this filter.',
      ctaTitle: 'Your project could be next on this list.',
      ctaSub: 'Let\'s talk about what you want to build.',
      ctaButton: 'Start a project',
    },
    about: {
      eyebrow: 'About',
      headline: 'A site that converts is better than a site that impresses',
      sub: 'One contact person, from brief to launch. With one goal in mind: your ROI.',
      whyEyebrow: 'Differentiators',
      whyTitle: 'What sets us apart.',
      differentiators: [
        { title: '15-day delivery', text: 'From project start to live site — 15 business days. No fluff, no waiting.' },
        { title: 'Real metrics only', text: 'Every decision is based on Search Console and GA4. No estimates, no spin.' },
        { title: 'No templates', text: 'Every site is built from scratch around your business. No pre-made themes.' },
        { title: 'Post-launch support', text: 'Available after launch. Monthly analytics, updates, and improvements.' },
        { title: 'Single contact', text: 'One point of contact from start to finish. No relaying PMs, no junior execution.' },
        { title: 'AI-search visible', text: 'Pages structured to appear in ChatGPT, Claude, Perplexity and other AI models — not just Google.' },
      ],
      statsEyebrow: 'By the numbers',
      stats: [
        { value: '15+',    label: 'Projects delivered' },
        { value: '1M+',  label: 'Google impressions' },
        { value: '100%',   label: 'Deadlines met' },
      ],
      ctaTitle: 'Ready for a site that actually works?',
      ctaSub: 'Tell me about your project. I reply fast and tell you straight if I\'m the right fit.',
      ctaButton: 'Start a conversation',
    },
    contact: {
      eyebrow: 'Contact',
      headline: 'Let\'s talk about your project.',
      sub: 'Fill in the form below, I\'ll get back to you within 24h. No pitch, no pressure.',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      company: 'Company / Project',
      serviceLabel: 'What you\'re looking for',
      services: ['Website', 'Custom CRM', 'SEO & Content', 'Not sure yet'],
      message: 'Message (optional)',
      submit: 'Send →',
      success: '✓ Message sent — I\'ll get back to you within 24h.',
      error: 'Something went wrong. Email me directly: loanrmb@gmail.com',
    },
    footer: {
      tagline: 'Custom web dev & CRM.',
      nav: ['Work', 'About', 'Contact'],
      navHref: ['/work', '/about', '/contact'],
      copy: '© 2025 Torquemade.',
      email: 'loanrmb@gmail.com',
    },
  },
} as const
