export type Lang = 'fr' | 'en'

export const strings = {
  fr: {
    nav: {
      work: 'Projets',
      services: 'Services',
      produits: 'Produits',
      about: 'À propos',
      blog: 'Blog',
      contact: 'Contact',
      cta: 'Démarrer un projet →',
      menuLabel: 'Ouvrir le menu',
      closeLabel: 'Fermer',
      servicesItems: [
        { label: 'Développement Web', href: '/services/web-dev', subtitle: 'Un site "simple", mais pensé pour avoir un réel impact.' },
        { label: 'CRM sur mesure', href: '/services/crm', subtitle: 'On construit **votre** CRM/logiciel pour votre activité, et il vous appartient.' },
        { label: 'Connexion Stock Magasin <> Site e-commerce', href: '/services/erp-ecommerce', subtitle: 'Connectez votre stock magasin à votre site internet en temps réel.' },
      ],
      produitsItems: [
        { label: 'TankLogic', href: '/tanklogic', subtitle: 'Le Logiciel dédié aux magasins de poissons et aquarium. Connecter votre être vivant en magasin à votre plateforme de vente en ligne en temps réel.' },
      ],
    },
    hero: {
      eyebrow: 'Studio',
      heroSubheadline: 'Web Dev — CRM sur mesure & Connexion Stock Magasin ↔ site e-commerce.',
      headline2: 'Du design à la base de données.',
      sub: 'Nous construisons des sites qui performent, et les systèmes derrière.',
      tagline: 'On ne construit pas de sites vitrines.',
      tagline2: 'On construit des systèmes.',
      tagline2Lead: 'On construit ',
      tagline2Accent: 'des systèmes.',
      cta1: 'Voir les projets',
      cta2: 'Nous contacter',
      heroCta1: 'Parlons de votre projet',
      heroCta2: 'Voir nos projets',
    },
    stats: [
      { value: '1M+', label: 'Impressions Google' },
      { value: '15+',   label: 'Projets livrés' },
      { value: '100%',  label: 'Délais respectés' },
    ],
    services: {
      eyebrow: 'Services',
      title: 'Ce qu\'on construit.',
      items: [
        {
          num: '01',
          title: 'Sites web',
          desc: 'Construits de zéro. Mobile-first, SEO-ready, livraison en 15 jours ouvrés.',
          href: '/services/web-dev',
        },
        {
          num: '02',
          title: 'CRM & Logiciel sur mesure',
          desc: 'Systèmes de réservation, CRM sur mesure pour votre entreprise, dashboards, construits autour de votre workflow exact.',
          href: '/services/crm',
        },
        {
          num: '03',
          title: 'Connexion stock ERP - Site e-commerce',
          desc: 'ERP existant ou logiciel sur mesure, votre stock synchronisé en temps réel avec votre Shopify.',
          href: '/services/erp-ecommerce',
        },
        {
          num: '04',
          title: 'SEO & Optimisation IA',
          desc: 'Contenu qui rank sur Google ET dans les réponses AI : ChatGPT, Perplexity, Claude, et autres.',
        },
      ],
    },
    servicesSection: {
      eyebrow: '',
      title: "De l'idée au système. Construit pour vous.",
      tabs: [
        {
          title: 'Sites web',
          desc: 'Next.js sur mesure, mobile-first, SEO-ready. Livraison 15 jours ouvrés.',
          tag: '',
        },
        {
          title: 'CRM & Logiciel sur mesure',
          desc: 'Réservations, dashboards, workflows métier, bâtis autour de votre process exact.',
          tag: 'CRM sur mesure',
        },
        {
          title: 'Connexion ERP · Stock',
          desc: 'Synchronisation temps réel entre votre ERP et votre site e-commerce.',
          tag: '',
        },
      ],
      erp: {
        stockTitle: 'Logiciel de stock',
        siteTitle: 'Site e-commerce',
        stockFooter: 'Connecté · Dernière sync 2s',
        siteFooter: '↻ Dernière sync : il y a 2s',
        colProduct: 'Produit',
        colSku: 'SKU',
        colStock: 'Stock',
        colPrice: 'Prix',
        colCategory: 'Catégorie',
        colStatus: 'Statut',
        statusActive: 'Actif',
        connectorSync: 'sync →',
        connectorPush: '→ push',
        apiLabel: 'API · Webhook',
        apiResult: '· 9 produits · 98ms',
        catWine: 'Vin',
        catChampagne: 'Champagne',
        caption: '',
        statusRupture: 'Rupture',
        apiUpdate: '↓ mise à jour en temps réel',
        apiCurrency: 'EUR',
      },
      seo: {
        pageSettings: 'Réglages de page',
        labelTitle: 'Titre',
        titleValue: 'Magasin de vin Genève | Cave…',
        labelDesc: 'Description de page',
        descValue:
          'Achetez vos vins en ligne — livraison sous 24h sur Genève. Bordeaux, Bourgogne, Champagne.',
        redirectsTitle: 'Redirections',
        oldUrl: 'Ancienne URL',
        newUrl: 'Nouvelle URL',
        aiTitle: 'Cité par les IA',
        aiRows: [
          { name: 'ChatGPT', quote: '"Meilleure cave en ligne…"' },
          { name: 'Perplexity', quote: '"Cave recommandée à…"' },
          { name: 'Claude', quote: '"Pour acheter du vin à…"' },
        ],
        sessions: 'sessions',
      },
      alts: {
        site: 'jetski-arcachon.fr — production',
        code: 'index.html — source',
        crmForm: 'CRM sur mesure — réservation',
        crmDash: 'Mes Rendez-vous — dashboard',
      },
    },
    home: {
      partnerTitle: 'Un seul interlocuteur pour tout votre écosystème digital',
      partnerBody: 'Site e-commerce, logiciel métier, stock connecté, nous construisons l\'ensemble et assurons que tout fonctionne ensemble.',
      erp: {
        title: 'Votre stock, votre site, votre logiciel — connectés.',
        subtitle: 'ERP existant ou sur mesure, nous le construisons selon vos besoins et le connectons à votre site e-commerce. Stock synchronisé en temps réel, commandes remontées automatiquement, zéro double saisie.',
        erpBox: 'ERP / Logiciel de gestion',
        syncBox: 'Synchronisation',
        siteBox: 'Site e-commerce',
        syncItem1: 'Stock',
        syncItem2: 'Prix',
        syncItem3: 'Commandes',
        comparisonWithoutHeader: 'Sans connexion ERP',
        comparisonWithHeader: 'Avec connexion ERP',
        comparisonRows: [
          ['Mise à jour manuelle du stock', 'Stock synchronisé en temps réel'],
          ['Erreurs de saisie fréquentes', 'Zéro double saisie'],
          ['Survente et ruptures de stock', 'Alertes de stock automatiques'],
          ['Commandes traitées à la main', 'Commandes remontées instantanément'],
          ['Aucune visibilité temps réel', 'Dashboard centralisé'],
          ['Données éparpillées entre 3 outils', 'Un seul système, une seule source de vérité'],
        ],
        ctaButton: 'En savoir plus',
      },
    },
    erpFeature: {
      eyebrow: 'Synchronisation en temps réel',
      syncLabel: 'Dernière sync : il y a {n}s',
    },
    workPreview: {
      eyebrow: 'Projets à la une',
      title: 'Des sites qui performent, pas juste de beaux designs.',
      cta: 'Voir tous les projets →',
    },
    testimonials: {
      eyebrow: 'Avis clients',
      title: 'Ce que disent nos clients.',
      items: [
        {
          quote: 'Loan a pris le temps d\'écouter et a proposé les solutions les plus adaptées. Le site a eu un impact énorme sur notre activité — les retours sont extrêmement positifs. Nous lui avons ensuite confié 2 missions supplémentaires pour mettre en avant 2 marques importantes via 2 sites séparés, avec le même résultat. Nous recommandons Loan pour sa disponibilité et son professionnalisme.',
          name: 'Pierre',
          role: 'Commercial · Sprint Motors, Bordeaux',
          url: 'https://sprintmotors.com',
          initials: 'P',
        },
        {
          quote: 'Je recommande vivement le professionnalisme de Loan pour la création de site web. Il a su écouter mes demandes et comprendre rapidement mes attentes. Je suis extrêmement satisfait de son travail. Merci pour la qualité, la disponibilité et la rapidité.',
          name: 'Paul',
          role: 'Gérant · Moto Passion 65, Tarbes',
          url: 'https://motopassion65.com',
          initials: 'P',
        },
      ],
    },
    cta: {
      title: 'Parlons de votre projet.',
      sub: 'Remplissez le formulaire, on revient vers vous dans les 24h. Pas de pitch, pas de pression.',
      button: 'Démarrer une conversation',
    },
    work: {
      eyebrow: 'Projets',
      headline: 'Projets à la une.',
      sub: 'De vrais projets, avec des métriques réelles, tirées de Google Search Console et GA4.',
      filterAll: 'Tous',
      filterWeb: 'Sites web',
      filterLogiciel: 'CRM & Systèmes',
      filterSeo: 'SEO & Contenu',
      visitSite: 'Voir le site →',
      noMatch: 'Aucun projet ne correspond à ce filtre.',
      ctaTitle: 'Parlons de votre projet.',
      ctaSub: 'Remplissez le formulaire, on revient vers vous dans les 24h. Pas de pitch, pas de pression.',
      ctaButton: 'Démarrer un projet',
    },
    about: {
      eyebrow: 'À propos',
      headline: 'Un site qui convertit vaut mieux qu\'un site qui impressionne.',
      sub: 'Un seul interlocuteur, du brief au lancement. Avec un objectif en tête : votre ROI.',
      whyEyebrow: 'Différenciateurs',
      whyTitle: 'Ce qui nous différencie.',
      differentiators: [
        { title: 'Livraison en 15 jours', text: 'Du début du projet à la livraison du site live, 15 jours ouvrés. Pas de blabla, pas d\'attente inutile.' },
        { title: 'Métriques réelles uniquement', text: 'Chaque décision est basée sur Search Console et GA4. Pas d\'estimations, pas de spin.' },
        { title: 'Pas de template', text: 'Chaque site est construit de zéro autour de votre business. Aucun thème prémâché.' },
        { title: 'Support post-lancement', text: 'Disponible après le lancement. Analyses mensuelles, mises à jour, évolutions.' },
        { title: 'Interlocuteur unique', text: 'Un seul contact du début à la fin. Pas de chef de projet qui relaie, pas de junior.' },
        { title: 'Visible sur l\'IA', text: 'Vos pages sont structurées pour apparaître dans ChatGPT, Claude et Perplexity et autres.' },
      ],
      statsEyebrow: 'En chiffres',
      stats: [
        { value: '15+',    label: 'Projets livrés' },
        { value: '1M+',  label: 'Impressions Google' },
        { value: '100%',   label: 'Délais respectés' },
      ],
      ctaTitle: 'Prêt pour un site qui performe vraiment ?',
      ctaSub: 'Parlez-nous de votre projet. Nous répondons vite et vous disons honnêtement si nous sommes la bonne solution.',
      ctaButton: 'Démarrer une conversation',
    },
    webDev: {
      eyebrow: 'Services',
      hero: 'Le bon site pour le bon projet',
      intro: 'Tous les sites ne se ressemblent pas. Selon votre activité, vos objectifs et votre façon de vendre, nous choisissons la technologie la plus adaptée, et nous vous expliquons pourquoi.',
      nextjsTitle: 'Site Next.js sur mesure',
      nextjsBody: 'Pour les entreprises de services, studios, agences et marques qui ont besoin d\'un site entièrement personnalisé. Aucune contrainte de plateforme, aucun template, tout est construit de zéro autour de votre identité et de vos objectifs. Performance maximale, flexibilité totale, intégrations sur mesure (CRM, API, outils métier).',
      nextjsFor: 'Idéal pour tout type de projet : entreprise de BTP, cabinet, restaurant, artisan, agence, studio, SaaS, marque, que vous ayez besoin d\'un site vitrine, d\'un site qui génère des leads, ou d\'un outil plus complexe avec des intégrations sur mesure.',
      shopifyTitle: 'Site Shopify e-commerce',
      shopifyBody: 'Pour les commerces qui vendent en ligne. Shopify est la plateforme e-commerce la plus aboutie du marché : gestion produits intuitive, checkout optimisé, paiements intégrés, fiabilité éprouvée. Nous construisons votre boutique de A à Z, design sur mesure, migration catalogue, configuration complète.',
      shopifyFor: 'Idéal pour : boutiques en ligne, magasins avec vente physique et digitale, marques produits, revendeurs.',
      differenceTitle: 'Quelle différence concrètement ?',
      differenceHeaderAspect: 'Aspect',
      differenceHeaderNextjs: 'Next.js',
      differenceHeaderShopify: 'Shopify',
      differenceItems: [
        { aspect: 'Objectif principal', nextjs: 'Présenter, convaincre, générer des leads', shopify: 'Vendre des produits en ligne' },
        { aspect: 'Gestion produits', nextjs: 'Manuelle ou via CMS/API', shopify: 'Interface dédiée, native et intuitive' },
        { aspect: 'Checkout & paiements', nextjs: 'Intégration sur mesure', shopify: 'Intégré, optimisé, prêt à l\'emploi' },
        { aspect: 'Flexibilité design', nextjs: 'Totale — aucune contrainte', shopify: 'Élevée dans le cadre Shopify' },
        { aspect: 'Connexion à vos outils', nextjs: 'Illimitée, votre site peut communiquer avec n\'importe quel logiciel : CRM, ERP, outil de facturation, base de données...', shopify: 'Via les apps Shopify ou des connecteurs développés sur mesure' },
      ],
      deliveryTitle: 'Dans tous les cas, on livre',
      delivery: [
        'Design sur mesure',
        'Mobile-first et optimisé SEO',
        'Migration depuis votre ancien site',
        '100% responsive',
        'Formation à la prise en main',
        'Support post-lancement',
      ],
      ctaTitle: 'Prêt pour un site qui convertit ?',
      ctaSub: 'Parlez-nous de votre projet. Nous revenons vers vous dans les 24h.',
      ctaButton: 'Démarrer une conversation',
    },
    crm: {
      eyebrow: 'Services',
      hero: 'Des outils pensés pour votre métier',
      intro: 'Les logiciels génériques ne correspondent jamais parfaitement à votre façon de travailler. Nous construisons des CRM et outils de gestion sur mesure, adaptés à vos processus.',
      targetsTitle: 'Qui en a besoin ?',
      targets: [
        {
          title: 'Entreprises de location',
          desc: 'Véhicules, matériel, équipements, gérez vos disponibilités, réservations et clients en un seul endroit.',
        },
        {
          title: 'Chauffeurs privés & VTC',
          desc: 'Courses, clients récurrents, facturation, un outil pensé pour votre activité mobile.',
        },
        {
          title: 'Salles de sport & studios',
          desc: 'Abonnements, présences, cours collectifs, pilotez votre activité sans jongler entre dix outils.',
        },
        {
          title: 'Prestataires de services',
          desc: 'Agences, artisans, consultants, suivez vos prospects, devis, projets et relances depuis une seule interface.',
        },
        {
          title: 'Professions médicales & paramédicales',
          desc: 'Rendez-vous, patients, historique, une solution confidentielle et adaptée à votre pratique.',
        },
        {
          title: 'Tout métier avec des clients récurrents',
          desc: 'Si vous avez des clients, un historique à suivre et des actions à automatiser, un CRM sur mesure vous fait gagner du temps chaque jour.',
        },
      ],
      deliveryTitle: 'Ce qu\'on livre',
      delivery: [
        'CRM sur mesure adapté à vos processus exacts',
        'Systèmes de réservation et gestion de planning',
        'Tableaux de bord et reporting en temps réel',
        'Gestion clients, historique et suivi des interactions',
        'Automatisations : relances, notifications, rappels',
        'Gestion des devis, commandes et suivi commercial',
        'Accès multi-utilisateurs avec rôles et permissions',
        'Import / export de vos données existantes',
        'Intégrations tierces : email, calendrier, comptabilité',
        'Interface mobile-friendly, utilisable partout',
        'Évolutions et nouvelles fonctionnalités dans le temps',
        'Support dédié — un interlocuteur qui connaît votre outil',
      ],
      ctaTitle: 'Prêt pour un outil qui colle à votre métier ?',
      ctaSub: 'Parlez-nous de vos processus. Nous revenons vers vous dans les 24h.',
      ctaButton: 'Démarrer une conversation',
    },
    erp: {
      eyebrow: 'Services',
      hero: 'Votre stock et votre site, enfin synchronisés',
      intro: 'Votre ERP contient votre stock réel. Votre site affiche autre chose. Nous résolvons ce problème définitivement, en connectant vos systèmes ou en construisant l\'outil qu\'il vous faut.',
      shopifyTitle: 'Pourquoi Shopify ?',
      shopifyBody: 'Nous utilisons Shopify pour tous nos projets e-commerce. C\'est la plateforme la plus aboutie du marché : interface intuitive, écosystème d\'applications riche, checkout optimisé, fiabilité éprouvée. Vos équipes la prennent en main en quelques heures.',
      option1Badge: 'Option A',
      option1Title: 'Option A — Vous avez déjà un ERP',
      option1Subtitle: 'On connecte votre logiciel actuel à Shopify',
      option1Body: 'Votre SAGE, Cegid ou autre ERP reste en place. Nous construisons le connecteur qui synchronise votre stock avec Shopify en temps réel. Chaque vente en ligne déduit automatiquement dans votre ERP. Chaque modification de stock côté ERP se reflète immédiatement sur votre site. Vous ne changez rien à vos habitudes, votre équipe continue à travailler dans l\'outil qu\'elle connaît.',
      option1Delivery: [
        'Audit de votre ERP et de son API',
        'Développement du connecteur sur mesure',
        'Synchronisation stock bidirectionnelle en temps réel',
        'Déduction automatique à chaque commande Shopify',
        'Gestion des variantes (taille, couleur...)',
        'Tests et validation avant mise en production',
      ],
      option2Badge: 'Option B',
      option2Title: 'Option B — Vous avez besoin d\'un outil de gestion',
      option2Subtitle: 'On crée votre ERP stock sur mesure + on le connecte à Shopify',
      option2Body: 'Votre ERP actuel est vieillissant, mal adapté ou inexistant ? Nous construisons un logiciel de gestion de stock moderne, taillé pour votre activité, et connecté nativement à votre Shopify. Interface claire, prise en main rapide, abonnement mensuel sans licence annuelle.',
      option2Delivery: [
        'Logiciel de gestion de stock sur mesure',
        'Dashboard stock en temps réel',
        'Synchronisation Shopify bidirectionnelle native',
        'Déduction automatique à chaque vente',
        'Réception fournisseur par scan code-barres',
        'Gestion des fournisseurs et bons de commande',
        'Alertes stock bas configurables',
        'Migration depuis votre système actuel',
        'Abonnement mensuel — pas de licence annuelle',
      ],
      ctaTitle: 'Prêt à arrêter la ressaisie ?',
      ctaSub: 'Parlez-nous de votre stack actuel. Nous revenons vers vous dans les 24h.',
      ctaButton: 'Démarrer une conversation',
    },
    contact: {
      eyebrow: 'Contact',
      headline: 'Parlons de votre projet.',
      sub: 'Remplissez le formulaire ci-dessous, nous revenons vers vous dans les 24h. Pas de pitch, pas de pression.',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'Email',
      company: 'Entreprise / Projet',
      serviceLabel: 'Ce que vous cherchez',
      services: ['Site web', 'CRM sur mesure', 'SEO & Contenu', 'Connexion stock - site en ligne', 'TankLogic — poissons & coraux', 'Pas encore sûr(e)'],
      budgetLabel: 'Budget estimé',
      budgetOptional: '(optionnel)',
      currencyLabel: 'Devise',
      currencies: ['CHF', 'EUR', 'USD', 'GBP', 'CAD', 'PLN'],
      budgets: ['< 5 000', '5 000 – 10 000', '10 000 – 20 000', '20 000 +'],
      message: 'Message (optionnel)',
      multipleChoice: 'choix multiple',
      sending: 'Envoi...',
      submit: 'Envoyer →',
      success: '✓ Message envoyé, nous revenons vers vous dans les 24h.',
      error: 'Une erreur s\'est produite. Envoyez-nous un email : loanrmb@gmail.com',
    },
    footer: {
      tagline: 'Web dev & CRM sur mesure.',
      nav: ['Projets', 'À propos', 'Blog', 'Contact'],
      navHref: ['/work', '/about', '/blog', '/contact'],
      copy: '© 2025 Torquemade.',
      email: 'loanrmb@gmail.com',
      legal: 'Mentions légales',
      tanklogic: 'TankLogic — poissons & coraux',
    },
    blog: {
      eyebrow: 'Blog',
      headline: 'Ressources pour les\nprofessionnels du web\net du CRM.',
      sub: 'Stratégies, analyses et retours d\'expérience, sans jargon inutile.',
      backLabel: '← Blog',
      readingTime: 'min de lecture',
      updatedLabel: 'Dernière mise à jour :',
      featuredTitle: 'À la une',
      featuredRead: "Lire l'article",
      ctaEyebrow: 'Un projet ?',
      ctaTitle: 'Parlons de votre site web ou de votre CRM.',
      ctaButton: 'Prendre contact →',
    },
    seoSection: {
      title: 'SEO & Optimisation IA',
      subtitle: 'Visible sur Google. Cité par les IA.',
      card1: {
        title: 'Contenu qui se positionne',
        desc: 'Articles, pages service et fiches produit optimisés pour capturer du trafic qualifié sur le long terme.',
      },
      card2: {
        title: 'Métadonnées et structure',
        desc: 'Title tags, meta descriptions, balises H, structure d\'URL propre, chaque signal technique au bon niveau.',
      },
      card3: {
        title: 'Cité par les IA',
        desc: 'Structure sémantique et contenu d\'autorité qui remontent dans les réponses ChatGPT, Perplexity et Claude.',
      },
      item1: {
        title: 'Balises & métadonnées',
        desc: 'Title tags, meta descriptions et balises H, chaque page envoyée à Google avec les bons signaux.',
      },
      item2: {
        title: 'Mots-clés',
        desc: 'Recherche et stratégie de mots-clés ciblés selon votre secteur, vos services et votre zone géographique.',
      },
      item3: {
        title: 'Structure d\'URL & redirections',
        desc: 'URLs propres, redirections 301, architecture de site lisible par Google et compréhensible par vos clients.',
      },
      item4: {
        title: 'Core Web Vitals & performance',
        desc: 'LCP, FID, CLS, chaque page livrée avec un score Lighthouse vert. La vitesse est un facteur de classement.',
      },
      item5: {
        title: 'Articles de blog',
        desc: 'Contenus locaux et génériques qui captent les recherches longue traîne, et restent visibles des mois après publication.',
      },
      item6: {
        title: 'Cité par les IA',
        desc: 'Structure sémantique et contenu d\'autorité conçus pour apparaître dans les réponses ChatGPT, Perplexity, Claude et Gemini.',
      },
    },
    meta: {
      webDev: {
        title: 'Sites web Next.js & Shopify sur mesure | Torquemade',
        description: 'Sites Next.js et Shopify construits de zéro : mobile-first, optimisés SEO, intégrations CRM et API sur mesure. Livraison en 15 jours ouvrés.',
      },
      crm: {
        title: 'CRM sur mesure adapté à votre métier | Torquemade',
        description: 'CRM et outils de gestion sur mesure, taillés pour vos processus : réservations, tableaux de bord temps réel, automatisations et suivi client.',
      },
      erp: {
        title: 'Synchronisation stock ERP ↔ site e-commerce | Torquemade',
        description: 'Connexion en temps réel entre votre ERP (SAGE, Cegid…) et Shopify. Fin de la ressaisie : chaque vente déduit automatiquement votre stock réel.',
      },
      aquariumQc: {
        title: 'Synchro stock aquariophilie ↔ e-commerce (Québec) | Torquemade',
        description: 'Pour les boutiques de coraux et poissons au Québec : synchronisez caisse et boutique en ligne en temps réel. Fini le corail vendu deux fois. Chaque frag unique se retire du site à la seconde où il part en magasin.',
      },
    },
    aquariumQc: {
      eyebrow: 'Aquariophilie · Québec',
      hero: 'Votre corail s’est vendu deux fois : une fois en boutique, une fois en ligne.',
      intro:
        'Pour les boutiques de coraux et de poissons au Québec, chaque frag est une pièce unique. Nous connectons votre caisse et votre site en temps réel pour qu’un article vendu au comptoir disparaisse du site avant que le prochain client ne le commande.',

      problemTitle: 'Un corail n’est pas un t-shirt en taille M',
      problemBody: [
        'La plupart des logiciels de stock partent d’une hypothèse simple : un SKU, une quantité, un réassort. Un t-shirt en M, vous en avez douze, vous en vendez un, il en reste onze. L’aquariophilie ne fonctionne pas comme ça.',
        'Vos coraux sont vendus en WYSIWYG — « what you see is what you get ». Chaque frag est photographié individuellement, porte un prix unique et existe en quantité 1. Une fois parti, il n’y a pas de réassort : c’est une colonie vivante, pas un article de catalogue.',
        'Ajoutez à cela le vivant : poissons sous quarantaine, politiques DOA (dead on arrival), fenêtres d’expédition qui dépendent de la météo, packs chauffants l’hiver québécois. Et surtout, vous vendez partout à la fois — au comptoir à Laval ou Montréal, sur votre boutique en ligne, et souvent en direct sur les groupes Facebook et les ventes live.',
      ],
      problemPointsTitle: 'Ce qui rend votre stock ingérable en standard',
      problemPoints: [
        'Chaque corail = une pièce unique en quantité 1, photographiée, à prix propre.',
        'Aucun réassort possible : une fois vendu, l’article doit disparaître, pas se « remettre en stock ».',
        'Vente multi-canal simultanée : comptoir, site, groupes Facebook, ventes live.',
        'Vivant : quarantaine, DOA, avoirs, fenêtres d’expédition météo-dépendantes.',
      ],

      genericTitle: 'Pourquoi Shopify ou Lightspeed seul ne suffit pas',
      genericBody: [
        'Le problème n’est pas Shopify. Le problème n’est pas Lightspeed — dont le siège est d’ailleurs à Montréal et qui équipe une grande partie du commerce de détail québécois. Le problème, c’est qu’aucun des deux n’est la source de vérité de l’autre.',
        'Votre caisse tient un compteur. Votre site en tient un autre. Les applications de synchro grand public sont pensées pour des SKU classiques avec des quantités élevées et un réassort régulier — pas pour du vivant unique en quantité 1. Elles synchronisent par lots, toutes les quelques minutes. Sur un t-shirt, ce délai n’a aucune importance. Sur un corail unique, ces quelques minutes suffisent à ce qu’il soit encaissé au comptoir et commandé en ligne en même temps.',
        'Résultat : le survente. Vous annulez, vous remboursez, vous vous excusez auprès d’un client qui attendait précisément cette colonie. Et vous ressaisissez le stock à la main, le soir, sur deux systèmes qui ne se parlent pas.',
      ],

      solveTitle: 'Ce que Torquemade met en place',
      solveSubtitle: 'Une seule source de vérité, une déduction à la seconde.',
      solveBody:
        'Nous construisons la couche de synchronisation qui manque entre votre caisse et votre boutique en ligne — taillée pour le vivant unique, pas pour du prêt-à-porter.',
      solveDelivery: [
        'Source de vérité unique : un stock, pas deux compteurs qui divergent.',
        'Déduction en temps réel : une vente comptoir retire l’article du site en quelques secondes.',
        'Quantité 1 gérée nativement : le frag vendu passe automatiquement en « vendu » et se masque.',
        'Verrou de réservation : un panier en ligne bloque la pièce le temps du paiement.',
        'Gestion du vivant : statuts quarantaine, DOA, avoirs et fenêtres d’expédition.',
        'Multi-canal réel : comptoir, site et ventes directes réconciliés au même endroit.',
      ],

      techTitle: 'Comment fonctionne la synchro caisse → boutique en ligne',
      techBody:
        'Concrètement, nous relions vos systèmes existants avec une couche middleware légère. Pas de refonte : votre caisse et votre site restent les vôtres.',
      techSteps: [
        'Une vente se produit — au comptoir (Lightspeed, Square, système legacy) ou en ligne (Shopify).',
        'Un webhook déclenche instantanément notre couche de synchronisation.',
        'Le stock réel est déduit et l’article unique passe en « vendu ».',
        'La fiche produit se masque du site avant qu’un autre client ne la commande.',
        'Les cas particuliers — DOA, retour, avoir — remontent au bon endroit, sans ressaisie.',
      ],
      techNote:
        'Vous êtes sur un ERP ou un logiciel de caisse plus ancien ? C’est exactement notre spécialité : connecter le legacy au web. Voir notre service ',

      linkErpLabel: 'Synchronisation ERP ↔ e-commerce',
      linkCrmLabel: 'CRM sur mesure',
      linkCaseLabel: 'Étude de cas : concession moto',
      relatedTitle: 'À lire aussi',

      ctaTitle: 'Voyons votre stock en action',
      ctaSub: 'Décrivez-nous votre boutique et vos canaux de vente. On vous montre à quoi ressemblerait la synchro, sans engagement.',
      ctaButton: 'Réserver une démo',
    },

    tanklogic: {
      eyebrow: 'Un produit Torquemade',
      wordmark: 'TankLogic',
      heroTitle: 'Chaque spécimen compte.',
      heroSub: 'TankLogic est le logiciel de stock des détaillants qui vendent des poissons et coraux vivants à distance — de la cuve de vente à la preuve de livraison.',
      heroCta: 'Parlons de votre projet',

      serialTitle: 'Un animal, une fiche.',
      serialBody: [
        'TankLogic ne compte pas des quantités : il enregistre des individus. Chaque poisson, chaque colonie de corail a sa fiche — photo, identifiant, statut.',
        'C’est le modèle WYSIWYG de bout en bout : le client achète exactement l’animal qu’il voit, pas un exemplaire générique de la catégorie.',
      ],

      syncTitle: 'Vendu en magasin. Retiré du site.',
      syncBody: [
        'Une vente au comptoir retire le spécimen de votre boutique en ligne en temps réel. Le même animal ne peut plus être vendu deux fois — zéro survente, zéro double vente, aucune mise à jour manuelle.',
      ],

      mortalityTitle: 'Un clic pour la mortalité. Un dossier pour les litiges.',
      mortalityIntro: 'C’est la réalité du vivant : des pertes en cuve et des contestations à l’arrivée. TankLogic est construit autour des deux.',
      mortalityClickTitle: 'Déclarer une perte en un clic',
      mortalityClickBody: 'Côté magasin, un bouton sort immédiatement le spécimen du stock, enregistre le motif et horodate la sortie. Le journal de mortalité se construit tout seul, au fil de l’eau.',
      traceTitle: 'La preuve, spécimen par spécimen',
      traceBody: 'Photo avant expédition, historique de statuts, horodatages : chaque envoi laisse une trace. Quand un client conteste une livraison en invoquant un DOA, vous répondez avec un dossier — pas avec votre bonne foi.',

      ordersTitle: 'Les commandes, au même endroit.',
      ordersBody: [
        'Créez et gérez vos commandes directement depuis le logiciel de stock. Les spécimens réservés sont liés à la commande — plus de jonglage entre tableur, boîte mail et back-office.',
      ],

      analyticsTitle: 'Vos pertes deviennent des décisions.',
      analyticsBody: [
        'Taux de mortalité par fournisseur et par espèce, taux de DOA, meilleures ventes, marges. Les données saisies au fil de l’eau ressortent en décisions d’achat : quel fournisseur garder, quelle espèce arrêter, quoi recommander.',
      ],

      faqTitle: 'Questions fréquentes',
      faq: [
        {
          q: 'Comment éviter les chargebacks DOA quand je vends du corail à distance ?',
          a: 'Un litige DOA (mort à l’arrivée) se gagne sur la preuve, pas sur la bonne foi. Il faut pouvoir montrer quel spécimen précis a été vendu (fiche avec photo), dans quel état il est parti (photo d’emballage horodatée) et qu’il a bien été livré (preuve de livraison liée à la commande). TankLogic capture ces trois éléments automatiquement dans le workflow d’expédition et les assemble en un dossier PDF prêt à transmettre à votre prestataire de paiement.',
        },
        {
          q: 'Mon logiciel de caisse peut-il gérer des poissons vendus « à la pièce » (WYSIWYG) ?',
          a: 'Dans la plupart des cas, non. Les caisses et ERP généralistes modélisent le stock en quantités par SKU partagé. Un spécimen WYSIWYG est un SKU unique : deux clients ne peuvent pas acheter le même corail. Sans fiche par spécimen, la synchro vers votre site traite tout en compteurs et finit par survendre. TankLogic modélise chaque animal comme un enregistrement individuel, avec photo et statut propres.',
        },
        {
          q: 'Que se passe-t-il sur mon site quand un poisson meurt en cuve ?',
          a: 'Avec un stock générique : rien — l’annonce reste « disponible » jusqu’à votre prochaine correction manuelle, et un client peut commander un animal qui n’existe plus. Avec TankLogic : vous marquez le spécimen mort dans le journal de mortalité, et cette unité précise est retirée de votre boutique en ligne en temps réel.',
        },
        {
          q: 'TankLogic se connecte-t-il à ma boutique en ligne ?',
          a: 'Oui. TankLogic pousse les changements d’état (vente en magasin, mortalité, réservation) vers votre boutique en ligne en quelques secondes, et les commandes en ligne redescendent réserver le spécimen. Votre inventaire TankLogic reste la source de vérité unique.',
        },
        {
          q: 'Est-ce que je peux prouver l’état d’un animal au moment de l’expédition ?',
          a: 'Oui — c’est le rôle de la photo d’emballage : au moment de préparer la commande, une photo horodatée du spécimen et de son conditionnement est rattachée à la commande, sans étape manuelle supplémentaire. Combinée au scan QR à la livraison, elle documente l’état au départ et la date de réception.',
        },
        {
          q: 'Pour qui TankLogic est-il conçu ?',
          a: 'Pour les animaleries aquatiques qui vendent du vivant à distance : poissons marins ou d’eau douce, coraux, invertébrés — en particulier les boutiques WYSIWYG expédiant par transporteur, au Canada, aux États-Unis et en Europe francophone.',
        },
      ],

      ctaTitle: 'Parlons de votre boutique',
      ctaSub: 'Décrivez-nous vos spécimens, vos canaux de vente et votre volume d’expédition. On vous montre comment TankLogic s’articulerait autour de votre workflow.',
      ctaButton: 'Parlons de votre projet',
    },
  },

  en: {
    nav: {
      work: 'Work',
      services: 'Services',
      produits: 'Products',
      about: 'About',
      blog: 'Blog',
      contact: 'Contact',
      cta: 'Start a project →',
      menuLabel: 'Open menu',
      closeLabel: 'Close',
      servicesItems: [
        { label: 'Web Development', href: '/services/web-dev', subtitle: 'A straightforward site, built to make a real impact.' },
        { label: 'Custom CRM', href: '/services/crm', subtitle: 'We build **your** CRM/software for your business — and you own it.' },
        { label: 'In-Store Inventory <> E-commerce Website Real-Time Sync', href: '/services/erp-ecommerce', subtitle: 'Connect your in-store stock to your website in real time.' },
      ],
      produitsItems: [
        { label: 'TankLogic', href: '/tanklogic', subtitle: 'Software built for fish and aquarium stores. Sync your live inventory in-store with your online sales platform in real time.' },
      ],
    },
    hero: {
      eyebrow: 'Studio',
      heroSubheadline: 'Web Dev — Custom CRM & In-store Stock ↔ e-commerce sync.',
      headline2: 'From design to database.',
      sub: 'We build sites that perform, and the systems behind them.',
      tagline: 'We don\'t build showcase sites.',
      tagline2: 'We build systems.',
      tagline2Lead: 'We build ',
      tagline2Accent: 'systems.',
      cta1: 'See our work',
      cta2: 'Get in touch',
      heroCta1: "Let's talk",
      heroCta2: 'See our work',
    },
    stats: [
      { value: '1M+', label: 'Google impressions' },
      { value: '15+',   label: 'Projects delivered' },
      { value: '100%',  label: 'Deadlines met' },
    ],
    services: {
      eyebrow: 'Services',
      title: 'What we build.',
      items: [
        {
          num: '01',
          title: 'Websites',
          desc: 'Built from scratch. Mobile-first, SEO-ready, delivered in 15 business days.',
          href: '/services/web-dev',
        },
        {
          num: '02',
          title: 'Custom CRM & Software',
          desc: 'Booking systems, tailored CRMs, dashboards, built around your exact workflow.',
          href: '/services/crm',
        },
        {
          num: '03',
          title: 'ERP - E-commerce connection',
          desc: 'Existing ERP or custom software, your inventory synced in real time with your Shopify.',
          href: '/services/erp-ecommerce',
        },
        {
          num: '04',
          title: 'SEO & AI Optimization',
          desc: 'Content that ranks on Google AND appears in AI answers: ChatGPT, Perplexity, Claude & other models.',
        },
      ],
    },
    servicesSection: {
      eyebrow: '',
      title: 'From idea to system. Built for you.',
      tabs: [
        {
          title: 'Websites',
          desc: 'Custom Next.js, mobile-first, SEO-ready. Delivered in 15 business days.',
          tag: '',
        },
        {
          title: 'Custom CRM & Software',
          desc: 'Bookings, dashboards, business workflows, built around your exact process.',
          tag: 'Custom CRM',
        },
        {
          title: 'ERP · Inventory sync',
          desc: 'Real-time synchronization between your ERP and your e-commerce site.',
          tag: '',
        },
      ],
      erp: {
        stockTitle: 'Inventory software',
        siteTitle: 'E-commerce site',
        stockFooter: 'Connected · Last sync 2s',
        siteFooter: '↻ Last sync: 2s ago',
        colProduct: 'Product',
        colSku: 'SKU',
        colStock: 'Stock',
        colPrice: 'Price',
        colCategory: 'Category',
        colStatus: 'Status',
        statusActive: 'Active',
        connectorSync: 'sync →',
        connectorPush: '→ push',
        apiLabel: 'API · Webhook',
        apiResult: '· 9 products · 98ms',
        catWine: 'Wine',
        catChampagne: 'Champagne',
        caption: '',
        statusRupture: 'Out of stock',
        apiUpdate: '↓ real-time update',
        apiCurrency: 'USD',
      },
      seo: {
        pageSettings: 'Page Settings',
        labelTitle: 'Title',
        titleValue: 'Geneva wine shop | Cellar…',
        labelDesc: 'Page Description',
        descValue:
          'Buy your wines online — 24h delivery across Geneva. Bordeaux, Burgundy, Champagne.',
        redirectsTitle: 'Redirects',
        oldUrl: 'Old URL',
        newUrl: 'New URL',
        aiTitle: 'Cited by AI',
        aiRows: [
          { name: 'ChatGPT', quote: '"Best online cellar…"' },
          { name: 'Perplexity', quote: '"Recommended cellar in…"' },
          { name: 'Claude', quote: '"To buy wine in…"' },
        ],
        sessions: 'sessions',
      },
      alts: {
        site: 'jetski-arcachon.fr — production',
        code: 'index.html — source',
        crmForm: 'Custom CRM — booking',
        crmDash: 'My Appointments — dashboard',
      },
    },
    home: {
      partnerTitle: 'One partner for your entire digital ecosystem',
      partnerBody: 'E-commerce site, business software, connected inventory, we build the whole stack and make sure everything works together.',
      erp: {
        title: 'Your inventory, your site, your software — connected.',
        subtitle: 'Existing ERP or custom-built, we build it around your business needs and connect it to your e-commerce site. Real-time stock sync, automatic order flow, zero double entry.',
        erpBox: 'ERP / Management Software',
        syncBox: 'Synchronization',
        siteBox: 'E-commerce site',
        syncItem1: 'Stock',
        syncItem2: 'Prices',
        syncItem3: 'Orders',
        comparisonWithoutHeader: 'Without ERP connection',
        comparisonWithHeader: 'With ERP connection',
        comparisonRows: [
          ['Manual stock updates', 'Real-time stock sync'],
          ['Frequent data entry errors', 'Zero double entry'],
          ['Overselling and stockouts', 'Automatic stock alerts'],
          ['Orders processed by hand', 'Orders flow back instantly'],
          ['No real-time visibility', 'Centralized dashboard'],
          ['Data scattered across 3 tools', 'One system, one source of truth'],
        ],
        ctaButton: 'Learn more',
      },
    },
    erpFeature: {
      eyebrow: 'Real-time synchronization',
      syncLabel: 'Last sync: {n}s ago',
    },
    workPreview: {
      eyebrow: 'Featured work',
      title: 'Sites that perform, not just look good.',
      cta: 'See all projects →',
    },
    testimonials: {
      eyebrow: 'Client reviews',
      title: 'What our clients say.',
      items: [
        {
          quote: 'Loan took the time to listen and proposed the most adapted solutions. The website had a huge impact on our business — the feedback has been extremely positive. We then entrusted him with 2 additional missions to highlight 2 important brands through 2 separate sites, with the same result. We highly recommend Loan for his availability and professionalism.',
          name: 'Pierre',
          role: 'Salesman · Sprint Motors, Bordeaux',
          url: 'https://sprintmotors.com',
          initials: 'P',
        },
        {
          quote: 'I highly recommend Loan\'s professionalism for website creation. He listened to my requests and quickly understood my expectations. I am extremely satisfied with his work. Thank you for the quality, availability, and speed.',
          name: 'Paul',
          role: 'Owner · Moto Passion 65, Tarbes',
          url: 'https://motopassion65.com',
          initials: 'P',
        },
      ],
    },
    cta: {
      title: 'Let\'s build something.',
      sub: 'Fill in the form, I\'ll get back to you within 24h. No pitch, no pressure.',
      button: 'Start a conversation',
    },
    work: {
      eyebrow: 'Work',
      headline: 'Featured work.',
      sub: 'Real projects, real metrics, pulled directly from Google Search Console and GA4.',
      filterAll: 'All',
      filterWeb: 'Websites',
      filterLogiciel: 'CRM & Systems',
      filterSeo: 'SEO & Content',
      visitSite: 'Visit site →',
      noMatch: 'No projects match this filter.',
      ctaTitle: 'Your project could be next on this list.',
      ctaSub: 'Let\'s talk about what you want to build.',
      ctaButton: 'Start a project',
    },
    about: {
      eyebrow: 'About',
      headline: 'A site that converts is better than a site that impresses',
      sub: 'One contact person, from brief to launch. With one goal in mind: your ROI.',
      whyEyebrow: 'Differentiators',
      whyTitle: 'What sets us apart.',
      differentiators: [
        { title: '15-day delivery', text: 'From project start to live site, 15 business days. No fluff, no waiting.' },
        { title: 'Real metrics only', text: 'Every decision is based on Search Console and GA4. No estimates, no spin.' },
        { title: 'No templates', text: 'Every site is built from scratch around your business. No pre-made themes.' },
        { title: 'Post-launch support', text: 'Available after launch. Monthly analytics, updates, and improvements.' },
        { title: 'Single contact', text: 'One point of contact from start to finish. No relaying PMs, no junior execution.' },
        { title: 'AI-search visible', text: 'Pages structured to appear in ChatGPT, Claude, Perplexity and other AI models — not just Google.' },
      ],
      statsEyebrow: 'By the numbers',
      stats: [
        { value: '15+',    label: 'Projects delivered' },
        { value: '1M+',  label: 'Google impressions' },
        { value: '100%',   label: 'Deadlines met' },
      ],
      ctaTitle: 'Ready for a site that actually works?',
      ctaSub: 'Tell me about your project. I reply fast and tell you straight if I\'m the right fit.',
      ctaButton: 'Start a conversation',
    },
    webDev: {
      eyebrow: 'Services',
      hero: 'The right site for the right project',
      intro: 'Not all websites are the same. Depending on your business, your goals and how you sell, we choose the right technology, and explain why.',
      nextjsTitle: 'Custom Next.js website',
      nextjsBody: 'For service businesses, studios, agencies and brands that need a fully custom site. No platform constraints, no templates, everything built from scratch around your identity and goals. Maximum performance, total flexibility, custom integrations (CRM, API, business tools).',
      nextjsFor: 'Ideal for any type of project: construction company, practice, restaurant, craftsman, agency, studio, SaaS, brand, whether you need a showcase site, a lead generation site, or a more complex tool with custom integrations.',
      shopifyTitle: 'Shopify e-commerce website',
      shopifyBody: 'For businesses that sell online. Shopify is the most complete e-commerce platform available: intuitive product management, optimized checkout, integrated payments, proven reliability. We build your store from A to Z, custom design, catalogue migration, full configuration.',
      shopifyFor: 'Ideal for: online stores, retailers with physical and digital sales, product brands, resellers.',
      differenceTitle: 'What\'s the actual difference?',
      differenceHeaderAspect: 'Aspect',
      differenceHeaderNextjs: 'Next.js',
      differenceHeaderShopify: 'Shopify',
      differenceItems: [
        { aspect: 'Primary goal', nextjs: 'Present, convince, generate leads', shopify: 'Sell products online' },
        { aspect: 'Product management', nextjs: 'Manual or via CMS/API', shopify: 'Dedicated, native, intuitive interface' },
        { aspect: 'Checkout & payments', nextjs: 'Custom integration', shopify: 'Built-in, optimized, ready to use' },
        { aspect: 'Design flexibility', nextjs: 'Total — no constraints', shopify: 'High within the Shopify framework' },
        { aspect: 'Connection to your tools', nextjs: 'Unlimited, your site can communicate with any software: CRM, ERP, invoicing tool, database...', shopify: 'Via Shopify apps or custom-built connectors' },
      ],
      deliveryTitle: 'In every case, we deliver',
      delivery: [
        'Custom design',
        'Mobile-first and SEO optimized',
        'Migration from your existing site',
        'Fully responsive',
        'Onboarding training',
        'Post-launch support',
      ],
      ctaTitle: 'Ready for a site that converts?',
      ctaSub: 'Tell us about your project. We\'ll get back to you within 24h.',
      ctaButton: 'Start a conversation',
    },
    crm: {
      eyebrow: 'Services',
      hero: 'Software built around your business',
      intro: 'Generic software never fits perfectly. We build custom CRMs and management tools tailored to your exact processes.',
      targetsTitle: 'Who needs it?',
      targets: [
        {
          title: 'Rental businesses',
          desc: 'Vehicles, equipment, gear, manage your availability, bookings and clients in one place.',
        },
        {
          title: 'Private drivers & ride services',
          desc: 'Rides, recurring clients, invoicing, a tool built for your mobile business.',
        },
        {
          title: 'Gyms & fitness studios',
          desc: 'Memberships, attendance, group classes, run your business without juggling ten different tools.',
        },
        {
          title: 'Service providers',
          desc: 'Agencies, tradespeople, consultants, track your leads, quotes, projects and follow-ups from one interface.',
        },
        {
          title: 'Medical & paramedical practices',
          desc: 'Appointments, patients, history, a confidential solution adapted to your practice.',
        },
        {
          title: 'Any business with recurring clients',
          desc: 'If you have clients, history to track and actions to automate, a custom CRM saves you time every day.',
        },
      ],
      deliveryTitle: 'What we deliver',
      delivery: [
        'CRM tailored to your exact processes',
        'Booking systems and schedule management',
        'Real-time dashboards and reporting',
        'Client management, history and interaction tracking',
        'Automations: follow-ups, notifications, reminders',
        'Quote, order and sales pipeline management',
        'Multi-user access with roles and permissions',
        'Import / export of your existing data',
        'Third-party integrations: email, calendar, accounting',
        'Mobile-friendly interface, usable anywhere',
        'Ongoing improvements and new features over time',
        'Dedicated support — someone who knows your tool',
      ],
      ctaTitle: 'Ready for a tool built around your business?',
      ctaSub: 'Tell us about your processes. We\'ll get back to you within 24h.',
      ctaButton: 'Start a conversation',
    },
    erp: {
      eyebrow: 'Services',
      hero: 'Your inventory and your store, finally in sync',
      intro: 'Your ERP holds your real inventory. Your website shows something else. We fix this permanently, by connecting your systems or building the tool you need.',
      shopifyTitle: 'Why Shopify?',
      shopifyBody: 'We use Shopify for all our e-commerce projects. It\'s the most complete platform on the market: intuitive interface, rich app ecosystem, optimized checkout, proven reliability. Your team gets up to speed in hours.',
      option1Badge: 'Option A',
      option1Title: 'Option A — You already have an ERP',
      option1Subtitle: 'We connect your existing software to Shopify',
      option1Body: 'Your SAGE, Cegid or other ERP stays in place. We build the connector that syncs your inventory with Shopify in real time. Every online sale automatically deducts in your ERP. Every stock change on the ERP side instantly reflects on your site. Nothing changes for your team, they keep working in the tool they know.',
      option1Delivery: [
        'Audit of your ERP and its API',
        'Custom connector development',
        'Real-time two-way inventory sync',
        'Automatic deduction on every Shopify order',
        'Variant management (size, color...)',
        'Testing and validation before go-live',
      ],
      option2Badge: 'Option B',
      option2Title: 'Option B — You need a management tool',
      option2Subtitle: 'We build your custom stock ERP + connect it to Shopify',
      option2Body: 'Your current ERP is outdated, ill-suited or nonexistent? We build a modern stock management tool, tailored to your business, natively connected to your Shopify. Clean interface, fast onboarding, monthly subscription with no annual license.',
      option2Delivery: [
        'Custom stock management software',
        'Real-time stock dashboard',
        'Native two-way Shopify sync',
        'Automatic deduction on every sale',
        'Barcode scanning for supplier deliveries',
        'Supplier and purchase order management',
        'Configurable low-stock alerts',
        'Migration from your current system',
        'Monthly subscription — no annual license',
      ],
      ctaTitle: 'Ready to stop the re-entry?',
      ctaSub: 'Tell us about your current stack. We\'ll get back to you within 24h.',
      ctaButton: 'Start a conversation',
    },
    contact: {
      eyebrow: 'Contact',
      headline: 'Let\'s talk about your project.',
      sub: 'Fill in the form below, We\'ll get back to you within 24h. No pitch, no pressure.',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      company: 'Company / Project',
      serviceLabel: 'What you\'re looking for',
      services: ['Website', 'Custom CRM', 'SEO & Content', 'Stock sync - online shop', 'TankLogic — fish & coral', 'Not sure yet'],
      budgetLabel: 'Estimated budget',
      budgetOptional: '(optional)',
      currencyLabel: 'Currency',
      currencies: ['CHF', 'EUR', 'USD', 'GBP', 'CAD', 'PLN'],
      budgets: ['< 5,000', '5,000 – 10,000', '10,000 – 20,000', '20,000 +'],
      message: 'Message (optional)',
      multipleChoice: 'multiple choice',
      sending: 'Sending...',
      submit: 'Send →',
      success: '✓ Message sent, I\'ll get back to you within 24h.',
      error: 'Something went wrong. Email me directly: loanrmb@gmail.com',
    },
    footer: {
      tagline: 'Custom web dev & CRM.',
      nav: ['Work', 'About', 'Blog', 'Contact'],
      navHref: ['/work', '/about', '/blog', '/contact'],
      copy: '© 2025 Torquemade.',
      email: 'loanrmb@gmail.com',
      legal: 'Legal Notice',
      tanklogic: 'TankLogic — fish & coral',
    },
    blog: {
      eyebrow: 'Blog',
      headline: 'Resources for web\nand CRM professionals.',
      sub: 'Strategy, analysis and real-world experience, no unnecessary jargon.',
      backLabel: '← Blog',
      readingTime: 'min read',
      updatedLabel: 'Last updated:',
      featuredTitle: 'Featured',
      featuredRead: 'Read article',
      ctaEyebrow: 'A project in mind?',
      ctaTitle: 'Let\'s talk about your website or CRM.',
      ctaButton: 'Get in touch →',
    },
    seoSection: {
      title: 'SEO & AI Optimisation',
      subtitle: 'Ranked on Google. Cited by AI.',
      card1: {
        title: 'Content that ranks',
        desc: 'Articles, service pages and product sheets optimised to capture qualified traffic over time.',
      },
      card2: {
        title: 'Metadata and structure',
        desc: 'Title tags, meta descriptions, H tags, clean URL structure, every technical signal dialled in.',
      },
      card3: {
        title: 'Cited by AI',
        desc: 'Semantic structure and authority content that surface your site in ChatGPT, Perplexity and Claude answers.',
      },
      item1: {
        title: 'Tags & metadata',
        desc: 'Title tags, meta descriptions and H tags, every page sending the right signals to Google.',
      },
      item2: {
        title: 'Keywords',
        desc: 'Keyword research and strategy tailored to your sector, services and geographic area.',
      },
      item3: {
        title: 'URL structure & redirects',
        desc: 'Clean URLs, 301 redirects, site architecture readable by Google and understandable by your customers.',
      },
      item4: {
        title: 'Core Web Vitals & performance',
        desc: 'LCP, FID, CLS, every page delivered with a green Lighthouse score. Speed is a ranking factor.',
      },
      item5: {
        title: 'Blog articles',
        desc: 'Local and general content capturing long-tail searches, staying visible for months after publication.',
      },
      item6: {
        title: 'Cited by AI',
        desc: 'Semantic structure and authority content designed to surface in ChatGPT, Perplexity, Claude and Gemini answers.',
      },
    },
    meta: {
      webDev: {
        title: 'Custom Next.js & Shopify Websites | Torquemade',
        description: 'Next.js and Shopify sites built from scratch: mobile-first, SEO-optimized, with custom CRM and API integrations. Delivered in 15 business days.',
      },
      crm: {
        title: 'Custom CRM Built for Your Trade | Torquemade',
        description: 'Bespoke CRM and management tools tailored to your processes: bookings, real-time dashboards, automations and client tracking.',
      },
      erp: {
        title: 'ERP ↔ E-commerce Inventory Sync | Torquemade',
        description: 'Real-time connection between your ERP (SAGE, Cegid…) and Shopify. No more re-keying: every online sale deducts from your real stock automatically.',
      },
      aquariumEn: {
        title: 'Coral & Livestock Inventory Sync for Aquarium Shops | Torquemade',
        description: 'Selling WYSIWYG coral across Canada? Stop overselling one-of-a-kind frags. We sync your POS, Shopify store and live drops in real time, so a sold frag leaves the site instantly.',
      },
      aquariumQc: {
        title: 'Aquarium Inventory ↔ E-commerce Sync (Quebec) | Torquemade',
        description: 'For coral and fish stores in Quebec: sync your POS and online store in real time. No more selling the same coral twice. Every one-of-a-kind frag leaves your site the second it sells in-store.',
      },
    },
    // English-primary market page (anglophone Canada). Rendered unconditionally
    // in English regardless of the FR/EN toggle so Googlebot indexes it as EN.
    aquariumEn: {
      eyebrow: 'Aquarium trade · Canada',
      hero: 'You drop 80 WYSIWYG frags on Friday. By Saturday, half your stock counts are wrong.',
      intro:
        'Coral shops in Toronto, Vancouver and Calgary don’t sell catalog SKUs — they sell one-of-a-kind livestock, across a counter, a Shopify store and a Friday-night live drop, all at once. We build the real-time sync layer that keeps those channels honest, so a frag that sells in one place disappears everywhere else before the next order lands.',

      problemTitle: 'Every frag is a serial number, not a stock level',
      problemBody: [
        'Retail inventory software assumes depth: one SKU, a quantity, a reorder point. Sell one of twelve mugs and eleven remain. Livestock breaks that model at the root. A WYSIWYG coral is photographed individually, priced on its own, and exists in quantity one. When it’s gone, there is no reorder — it was a living colony, not a catalog line.',
        'Now layer on how Canadian reef shops actually sell. New corals go up in weekly WYSIWYG batches — the Friday drop — where dozens of unique pieces hit the site at once and demand spikes for minutes, not days. The same tank is shoppable in-store, online, and often live on Instagram or Facebook at the same time. Whoever pays first should win; everyone else needs the item gone from their screen immediately.',
        'And it’s alive. Fish sit in quarantine before they’re sellable. Shipping runs on transit-time and weather windows — heat packs from Toronto to a prairie winter, cold packs in an Okanagan summer. DOA policies mean credits and reships, not clean refunds. None of that fits a simple in-stock / out-of-stock flag.',
      ],
      problemPointsTitle: 'Why off-the-shelf inventory can’t hold this',
      problemPoints: [
        'Every coral is a unique quantity-1 item — photographed, individually priced, never restocked.',
        'Weekly WYSIWYG drops spike demand on dozens of unique SKUs in minutes.',
        'The same livestock is sold in-store, on Shopify and on live streams simultaneously.',
        'Livestock rules: quarantine holds, DOA credits, weather-based shipping windows.',
      ],

      genericTitle: 'Why Shopify — and the sync apps bolted onto it — fall short',
      genericBody: [
        'This isn’t a knock on Shopify; it’s the right storefront for most reef shops. The gap is what happens between the storefront and the counter. Your POS keeps one count. Shopify keeps another. The popular sync apps were built for apparel and dry goods: high quantities, predictable restocks, batch updates every few minutes.',
        'On a t-shirt, a five-minute sync lag is invisible. On a single $400 acropora colony during a Friday drop, five minutes is the whole problem — long enough for the piece to be rung up at the counter and checked out online at the same time. Neither system knew about the other in time.',
        'The outcome is the tax every busy shop pays: overselling. You cancel the online order, issue the refund, and message a customer who drove across the GTA for exactly that frag. Then you re-key counts by hand after close, reconciling two systems that were never designed to agree.',
      ],

      solveTitle: 'What Torquemade builds',
      solveSubtitle: 'One source of truth, deduction measured in seconds.',
      solveBody:
        'We build the missing layer between your POS, your Shopify store and your live-sale channels — engineered for unique livestock and drop-day traffic, not steady catalog demand.',
      solveDelivery: [
        'One source of truth: a single stock, not two counts drifting apart after every sale.',
        'Real-time deduction: a sale on any channel pulls the item from the others within seconds.',
        'Quantity-1 native: a sold frag flips to “sold” and hides itself — no manual archiving.',
        'Reservation lock: an online cart holds the piece for the length of checkout.',
        'Drop tooling: batch-upload a Friday drop of dozens of WYSIWYG items in one pass.',
        'Livestock-aware: quarantine holds, DOA credits and transit windows handled, not faked.',
      ],

      techTitle: 'How the POS → Shopify → live-sale sync works',
      techBody:
        'We connect the systems you already run with a lightweight middleware layer. No rebuild, no migration — your POS and storefront stay exactly where they are.',
      techSteps: [
        'A sale fires on any channel — counter (Shopify POS, Lightspeed, Square) or online checkout.',
        'A webhook hits our sync layer the moment the sale is confirmed.',
        'Real stock is deducted and the unique item is flipped to “sold”.',
        'The product page hides itself before another shopper — or the live-sale queue — can order it.',
        'Livestock edge cases — DOA credit, reship, quarantine release — route to the right place, no re-keying.',
      ],
      techNote:
        'Running an older POS or a custom back office? Connecting legacy systems to the web is exactly what we do. See our ',

      linkErpLabel: 'ERP ↔ e-commerce sync service',
      linkCrmLabel: 'Custom CRM',
      linkCaseLabel: 'Case study: dealership CRM',
      relatedTitle: 'Related reading',

      ctaTitle: 'See your stock stay in sync',
      ctaSub: 'Tell us about your shop, your POS and your sales channels. We’ll show you exactly what the sync would look like on your next drop — no commitment.',
      ctaButton: 'Book a demo',
    },
    aquariumQc: {
      eyebrow: 'Aquarium trade · Quebec',
      hero: 'Your coral sold twice: once at the counter, once online.',
      intro:
        'For coral and fish stores in Quebec, every frag is a one-of-a-kind item. We connect your POS and your website in real time, so an item sold at the counter disappears from the site before the next customer can order it.',

      problemTitle: 'A coral isn’t a t-shirt in size M',
      problemBody: [
        'Most inventory software starts from a simple assumption: one SKU, one quantity, restock as needed. A medium t-shirt — you have twelve, you sell one, eleven remain. The aquarium trade doesn’t work like that.',
        'Your corals sell WYSIWYG — what you see is what you get. Each frag is photographed individually, carries its own price, and exists in quantity 1. Once it’s gone, there’s no restock: it’s a living colony, not a catalog item.',
        'Then add livestock: fish in quarantine, DOA (dead on arrival) policies, shipping windows that depend on the weather, heat packs through a Quebec winter. And above all, you sell everywhere at once — at the counter in Laval or Montreal, on your online store, and often live in Facebook groups and live sales.',
      ],
      problemPointsTitle: 'What makes your stock unmanageable off the shelf',
      problemPoints: [
        'Each coral = a unique item in quantity 1, photographed, individually priced.',
        'No restock possible: once sold, it must disappear, not go “back in stock”.',
        'Simultaneous multi-channel sales: counter, website, Facebook groups, live sales.',
        'Livestock: quarantine, DOA, store credit, weather-dependent shipping windows.',
      ],

      genericTitle: 'Why Shopify or Lightspeed alone isn’t enough',
      genericBody: [
        'The problem isn’t Shopify. It isn’t Lightspeed either — headquartered in Montreal and running a large share of Quebec retail. The problem is that neither one is the source of truth for the other.',
        'Your POS keeps a count. Your site keeps another. Consumer sync apps are built for classic SKUs with high quantities and regular restocking — not for unique livestock in quantity 1. They sync in batches, every few minutes. On a t-shirt, that delay doesn’t matter. On a one-of-a-kind coral, those few minutes are enough for it to be rung up at the counter and ordered online at the same time.',
        'The result: overselling. You cancel, you refund, you apologize to a customer who wanted precisely that colony. And you re-key the stock by hand, at night, across two systems that don’t talk to each other.',
      ],

      solveTitle: 'What Torquemade puts in place',
      solveSubtitle: 'A single source of truth, deduction to the second.',
      solveBody:
        'We build the missing sync layer between your POS and your online store — designed for unique livestock, not ready-to-wear.',
      solveDelivery: [
        'Single source of truth: one stock, not two counters that drift apart.',
        'Real-time deduction: a counter sale removes the item from the site within seconds.',
        'Quantity 1 handled natively: a sold frag flips to “sold” and hides itself automatically.',
        'Reservation lock: an online cart holds the item for the duration of checkout.',
        'Livestock handling: quarantine status, DOA, store credit and shipping windows.',
        'True multi-channel: counter, site and direct sales reconciled in one place.',
      ],

      techTitle: 'How the POS → online store sync works',
      techBody:
        'Concretely, we connect your existing systems with a lightweight middleware layer. No rebuild: your POS and your site stay yours.',
      techSteps: [
        'A sale happens — at the counter (Lightspeed, Square, legacy system) or online (Shopify).',
        'A webhook instantly triggers our sync layer.',
        'Real stock is deducted and the unique item flips to “sold”.',
        'The product page hides itself from the site before another customer can order it.',
        'Edge cases — DOA, return, store credit — land in the right place, with no re-keying.',
      ],
      techNote:
        'On an older ERP or POS? That’s exactly our specialty: connecting legacy to the web. See our ',

      linkErpLabel: 'ERP ↔ e-commerce sync',
      linkCrmLabel: 'Custom CRM',
      linkCaseLabel: 'Case study: motorcycle dealership',
      relatedTitle: 'Related reading',

      ctaTitle: 'Let’s see your stock in action',
      ctaSub: 'Tell us about your store and your sales channels. We’ll show you what the sync would look like, no commitment.',
      ctaButton: 'Book a demo',
    },

    tanklogic: {
      eyebrow: 'A Torquemade product',
      wordmark: 'TankLogic',
      heroTitle: 'Every specimen counts.',
      heroSub: 'TankLogic is the inventory software for retailers who sell live fish and coral by mail order — from the display tank to delivery proof.',
      heroCta: 'Let’s talk about your project',

      serialTitle: 'One animal, one record.',
      serialBody: [
        'TankLogic doesn’t count quantities: it records individuals. Every fish, every coral colony has its own card — photo, ID, status.',
        'It’s the WYSIWYG model end to end: the customer buys the exact animal they see, not a generic unit from a category.',
      ],

      syncTitle: 'Sold in store. Gone online.',
      syncBody: [
        'A counter sale removes the specimen from your online store in real time. The same animal can never be sold twice — no overselling, no double sales, no manual updates.',
      ],

      mortalityTitle: 'One click for mortality. One file for disputes.',
      mortalityIntro: 'This is the reality of live inventory: losses in the tank and disputes on arrival. TankLogic is built around both.',
      mortalityClickTitle: 'Log a loss in one click',
      mortalityClickBody: 'On the shop floor, one button pulls the specimen from stock immediately, records the reason and timestamps the removal. The mortality log builds itself, as you go.',
      traceTitle: 'Proof, specimen by specimen',
      traceBody: 'Pre-shipping photo, status history, timestamps: every shipment leaves a trail. When a customer disputes a delivery claiming DOA, you answer with a file — not with your good faith.',

      ordersTitle: 'Orders, in the same place.',
      ordersBody: [
        'Create and manage orders right inside your inventory software. Reserved specimens are linked to the order — no more juggling spreadsheets, inbox, and back office.',
      ],

      analyticsTitle: 'Losses become decisions.',
      analyticsBody: [
        'Mortality rate by supplier and by species, DOA rate, best sellers, margins. The data you log day to day comes back as buying decisions: which supplier to keep, which species to drop, what to reorder.',
      ],

      faqTitle: 'Frequently asked questions',
      faq: [
        {
          q: 'How do I avoid DOA chargebacks when I sell coral by mail order?',
          a: 'A DOA (dead-on-arrival) dispute is won on evidence, not good faith. You need to show which exact specimen was sold (record with photo), the condition it left in (timestamped packing photo), and that it was delivered (delivery proof linked to the order). TankLogic captures all three automatically inside your shipping workflow and assembles them into a ready-to-submit PDF evidence file for your payment provider.',
        },
        {
          q: 'Can my POS handle fish sold as individual (WYSIWYG) specimens?',
          a: 'Usually not. Generic POS and ERP systems model stock as quantities on a shared SKU. A WYSIWYG specimen is a unique SKU: two customers can’t buy the same coral. Without per-specimen records, the sync to your site treats everything as counters and eventually oversells. TankLogic models every animal as an individual record with its own photo and status.',
        },
        {
          q: 'What happens on my website when a fish dies in the tank?',
          a: 'With generic inventory: nothing — the listing stays “in stock” until your next manual correction, and a customer can order an animal that no longer exists. With TankLogic: you mark the specimen dead in the mortality log and that exact unit is pulled from your online store in real time.',
        },
        {
          q: 'Does TankLogic connect to my online store?',
          a: 'Yes. TankLogic pushes state changes (in-store sale, mortality, reservation) to your online store within seconds, and online orders flow back to reserve the specimen. Your TankLogic inventory stays the single source of truth.',
        },
        {
          q: 'Can I prove the condition of an animal at the moment it shipped?',
          a: 'Yes — that’s what the packing photo is for: at pack time, a timestamped photo of the specimen and its packaging is attached to the order, with no extra manual step. Combined with the QR scan at delivery, it documents condition at dispatch and date of receipt.',
        },
        {
          q: 'Who is TankLogic built for?',
          a: 'Aquatic livestock retailers selling live animals by mail order: marine or freshwater fish, coral, invertebrates — especially WYSIWYG shops shipping by courier, in Canada, the United States, and French-speaking Europe.',
        },
      ],

      ctaTitle: 'Let’s talk about your store',
      ctaSub: 'Tell us about your specimens, your sales channels, and your shipping volume. We’ll show you how TankLogic would fit around your workflow.',
      ctaButton: 'Let’s talk about your project',
    },
  },
} as const
