'use client'

import Link from 'next/link'
import { useLang } from '@/components/app-provider'

export function RoiSiteWebContent() {
  const lang = useLang()

  if (lang === 'en') return (
    <article className="blog-article">
      <h1 className="blog-article-title">Website ROI: How to Measure What It Really Brings You</h1>

      <p>
        "My site has 500 visits per month" is a vanity metric if none of those visits
        convert into a lead or client. Measuring a website's ROI means understanding the
        complete chain: from visit to contact, contact to quote, quote to client, client
        to revenue.
      </p>

      <h2>The metrics that really matter</h2>

      <ul>
        <li><strong>Visitor → contact conversion rate.</strong> How many visitors contact you? A local services site should convert 2–5% of traffic into qualified contacts. Below that, something is blocking — often the contact form, lack of CTAs, or service page content.</li>
        <li><strong>Contact → client conversion rate.</strong> Of leads generated by the site, how many become clients? Partly a lead quality question (does the site qualify well?) and partly your commercial process.</li>
        <li><strong>Average value of a client acquired via the site.</strong> If each site-generated client averages €800, and you have 10 clients/month via the site, your site generates €8,000/month. Put against the design and maintenance cost.</li>
        <li><strong>Cost per lead.</strong> (Annual site cost) / (annual leads generated). A €3,000 site that generates 60 qualified leads/year costs €50 per lead. Compared to Google Ads or a salesperson cost, often very competitive.</li>
      </ul>

      <h2>How to trace your client origins</h2>

      <p>
        The simplest way: ask each new client how they found your service. "Via Google,"
        "via your site," "via a friend" — in months, you have a clear picture of your
        site's contribution. The most precise way: Google Analytics 4 plus UTM parameters
        on your contact forms. Each incoming lead is traced to its source.
      </p>

      <hr />

      <p>
        <em>
          Want to set up ROI tracking for your site?{' '}
          <Link href="/contact">Contact us</Link>.
        </em>
      </p>

      <nav className="blog-related" aria-label="Related articles">
        <p className="blog-related-title">On the same topic</p>
        <ul>
          <li>
            <Link href="/blog/mesurer-succes-site-web">
              How to measure website success beyond traffic
            </Link>
          </li>
          <li>
            <Link href="/blog/site-web-meilleur-commercial">
              Why your website is your best salesperson in 2025
            </Link>
          </li>
          <li>
            <Link href="/blog/google-ads-vs-seo">
              Google Ads vs SEO: where to invest your digital budget first?
            </Link>
          </li>
        </ul>
      </nav>

    </article>
  )

  return (
    <article className="blog-article">
      <h1 className="blog-article-title">ROI d'un site web : comment mesurer ce que ça vous rapporte vraiment</h1>

      <p>
        "Mon site a 500 visites par mois" est une métrique de vanité si aucune de ces
        visites ne se convertit en lead ou en client. Mesurer le ROI d'un site web,
        c'est comprendre la chaîne complète : de la visite au contact, du contact
        au devis, du devis au client, du client au chiffre d'affaires.
      </p>

      <h2>Les métriques qui comptent vraiment</h2>

      <ul>
        <li>
          <strong>Taux de conversion visiteur → contact.</strong>
          Combien de visiteurs vous contactent ? Un site de services local devrait
          convertir entre 2 et 5 % de son trafic en contacts qualifiés. En dessous,
          quelque chose bloque — souvent le formulaire de contact, le manque de CTA
          ou le contenu de la page de service.
        </li>
        <li>
          <strong>Taux de conversion contact → client.</strong>
          Parmi les leads générés par le site, combien deviennent des clients ?
          C'est en partie une question de qualité du lead (le site qualifie-t-il
          bien ?) et en partie votre processus commercial.
        </li>
        <li>
          <strong>Valeur moyenne d'un client acquis via le site.</strong>
          Si chaque client généré via le site rapporte en moyenne 800 €, et que
          vous avez 10 clients par mois via le site, votre site génère 8 000 €/mois.
          À mettre en face du coût de conception et de maintenance.
        </li>
        <li>
          <strong>Coût par lead.</strong>
          (Coût annuel du site) / (nombre de leads générés par an). Un site à 3 000 €
          qui génère 60 leads qualifiés par an revient à 50 € le lead.
          Comparé au coût d'un lead via Google Ads ou un commercial, c'est souvent
          très compétitif.
        </li>
      </ul>

      <h2>Comment tracer l'origine de vos clients</h2>

      <p>
        La façon la plus simple : demandez à chaque nouveau client comment il a trouvé
        votre service. "Via Google", "via votre site", "via un ami" — en quelques mois,
        vous avez une image claire de la contribution de votre site à votre activité.
      </p>

      <p>
        La façon la plus précise : Google Analytics 4 + UTM parameters sur vos
        formulaires de contact. Chaque lead entrant est tracé jusqu'à sa source
        (requête Google, page d'atterrissage, canal). Vous voyez exactement quelles
        pages génèrent des leads et lesquelles ne convertissent pas.
      </p>

      <hr />

      <p>
        <em>
          Vous voulez mettre en place le tracking ROI de votre site ?{' '}
          <Link href="/contact">Contactez-nous</Link>.
        </em>
      </p>

      <nav className="blog-related" aria-label="Articles liés">
        <p className="blog-related-title">Sur le même sujet</p>
        <ul>
          <li>
            <Link href="/blog/mesurer-succes-site-web">
              Comment mesurer le succès d'un site web au-delà du trafic
            </Link>
          </li>
          <li>
            <Link href="/blog/site-web-meilleur-commercial">
              Pourquoi votre site web est votre meilleur commercial en 2025
            </Link>
          </li>
          <li>
            <Link href="/blog/google-ads-vs-seo">
              Google Ads vs SEO : où investir son budget digital en premier ?
            </Link>
          </li>
        </ul>
      </nav>

    </article>
  )
}
